class DataEsma {
  final int position;
  final String name;
  final int ebced;
  final String zikirgunu0;
  final String zikirgunu1;
  final String uzunAciklama;
  final String kisaAciklama;
  final String faziletKisa;
  final String faziletUzun;

  DataEsma(
      {this.position,
      this.name,
      this.ebced,
      this.zikirgunu0,
      this.zikirgunu1,
      this.uzunAciklama,
      this.kisaAciklama,
      this.faziletKisa,
      this.faziletUzun});
}

String Allah = "الله";

List<DataEsma> esmalar = [
  DataEsma(
      position: 1,
      name: "ALLAH c.c.",
      ebced: 66,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Allah zikrine devam eden kişinin derecesi hem Allah katında hem de insanlar katında artar. İnsanlar arasında; sevilen, sayılan, sözü geçen kıymetli bir kişi olur. Duaları kabul görür. Nefis şeytanının şerrinden kurtulur. Güneş doğarken gümüş veya altın levha üzerine Allah ismini yazan ve üzerinde taşıyan şeytan şerrinden korunur. Soğuk havada bu levha üzerinde iken Allah diye zikrederse soğuğu hissetmez. Balgam hastalığı olan kişi taşırsa balgam hastalığından kurtulur. Kişi 7 gün oruç tutup, gece yarısında 2 rekat Allah rızası için namaz kılıp, ardından 66 defa Allah zikrini yaparsa; Allah bir melek görevlendirir. O melek, o kişiyi tüm kötülüklerden koruduğu gibi, hal ve hareketlerinde, işlerinde o kişiyi yönlendirir, yönetir ve yardımcı olur. Allah ismini kağıda gül suyu, safran ve misk karışımıyla yazıp, üzerinde taşıyanı Allah her türlü kötülükten korur. Amir veya makam sahibi kişilerin yanında riayet görür. Düşmanlarına karşı galip gelir. Cuma günü oruçlu olarak, sabaha doğru gümüş yüzüğe Allah ismini yazıp, sağ elinin parmağına takan kişinin her isteği insanlar tarafından karşılanır. İşi görülür. Sol elinin parmağına takıp bir mahkemeye giden kişi haksızlığa uğramaz.Allah Cenabı Hakk’ın Celal ve Cemal gibi bütün isimlerini kapsamaktadır. Allah diye zikreden Cenabı Hakk’ı bütün isimleri ile anmış olur. Bütün isimler Allah isminde gizlidir. Diğer isimler Allah İsmi Azamına birer sıfattır. Allah ismi hiç bir isme sıfat olmaz. Cenabı Hakk’ın Zatına mahsus bütün isimlerin özellikleri Allah isminde vardır. Allah ismi; ruhi hastalıklardan, kalp katılığından, küfürden, maddi ve manevi bataklıktan, nefsin istek ve arzularından kurtulmak, düşmanlarını yenmek, merhamet sahibi olmak, Allah’ın istediği şekilde hayat sürmek, son nefeste imanlı ölmek, kalbin nurlanması, imanlı olması ve şifa bulmak, güç, kuvvet ve rızık kazanmak, gizli sırlara vakıf olmak, hem dünya, hemde ahiret saadetine ermek için zikredilir.",
      faziletKisa: "Tüm isim ve sıfatlan kendinde toplayan yüce Allah’ın zatının, başka hiçbir varlığa verilemeyen ismidir.",
      kisaAciklama:
          " Bütün eksikliklerden uzak, eşi benzeri bulunmayan, bütün isimleri kapsayan tek isim, tek ilah. İsimlerin sultanı.",
      uzunAciklama:
          "Gördüğümüz görmediğimiz, bildiğimiz bilmediğimiz bütün âlemlerin sâhibi ve mâliki, kâinatın yegâne yaratıcısı, her türlü övgüye ve ibâdete lâyık olan yüceler yücesi Rabbimizin doksan dokuz isminin bütün hususiyetlerini kendinde toplayan en kapsamlı özel adıdır."),
  DataEsma(
      position: 2,
      name: "ER-RAHMAN",
      ebced: 298,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Farz namazlarının ardından 100 defa Ya Rahman ismini zikreden; Allah’ın rızasını kazandığı gibi, Allah’ın nimetleride ona sunulur. 40 gün riyazet halinde 1000 defa Ya Rahman ismini zikredenin kalp gözü açılır. 5 V akit namazların ardından 2500 defa Ya Rahman ismini zikreden, her olaydan haberdar olur. Olay olmadan haberi olur. Er Rahman ismini; misk, safran, gül suyu karışımı mürekkep ile kağıda yazıp üzerinde taşıyan; insanlar arasında sevgi, saygı görür. Günde 290 defa zikredenin her arzusu gerçekleşir.",
      faziletKisa: "Dünya ve Ahirette Allah’ın sevgilisi olmak için okunur.",
      kisaAciklama: "Dünyadaki bütün yaratılmışlara merhamet eden.",
      uzunAciklama:
          "Rahmet ve merhamet; acıma, bağışlama, kalp yufkalığı, şefkat ve ihsân anlamlarına gelir. “Rahmân” ve “Rahîm” isimleri, “çok şefkat ve merhamet eden” anlamındadır. Kur’ân’da “Rahmân” ismi elli yedi, “Rahîm” ismi yüz on beş defa Allah’a nisbet edilmektedir. “Rahmân”, Allah’ın zâtî ismi, “Rahîm” ise fiilî isimlerindendir. “Rahmân”, zâtî ismi olduğundan Allah’tan başkasına isim olarak verilemez. Fiilî isimlerinden olan “Rahîm” ise başkasına isim olarak verilebilir. Allah’ın bu ismi bir kulda tecelli ederse, o kul merhamet kanatlarını bütün yaratıklara açar. Allah’ın rahmeti bütün yaratılmışları kapsar. Rahmetiyle, inanan inanmayan bütün insanlara rızıklarını ve nimetlerini bol bol vermektedir.Hz. Peygamber Allah’ın rahmetini şöyle anlatır: “Şüphesiz Allah’ın yüz rahmeti vardır. Bunlardan bir tanesini yaratıklarına vermiştir. Yaratıkların birbirlerine acımaları bu rahmet sebebiyledir. Allah’ın rahmetinin doksan dokuzu kıyâmet günü içindir.”"),
  DataEsma(
      position: 3,
      name: "ER-RAHÎM",
      ebced: 258,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Rahim ismini zikretmeye devam eden kişi; belalardan, kazalardan ve afetlerden korunur. Uykusunda ağlayan veya korkan çocuğun üzerine 269 defa Er Rahim isminin yazıldığı kağıt konulursa; çocuk bu durumdan kurtulur. 5 vakit namazlarının sonunda Ya Rahim ismini 269 defa okuyanın ahlakı düzelir. Rızkı ve bereketi artar. Hastaysa şifa bulur. Tüm nimetler okuyanın ayağına gelir. Errahmanirrahim veya Ya Rahman Ya Rahim isimlerini zikredenler; sıkıntıdan, darlıktan ve korkularından kurtulurlar. Günde 100 defa okuyanın kalbi yumuşar, Allah’ın rahmetini kazanır. Kötülüklerden muhafaza olur.",
      faziletKisa: "Maddi ve Manevi Rızıklar için okunur.",
      kisaAciklama:
          "Ahirette, müminlere sonsuz ihsanda, lütufta ve ikramda bulunan.",
      uzunAciklama:
          "Pek çok merhamet edici, verdiği nimetleri iyi kullananları daha büyük nimetler vermek suretiyle mükâfâtlandırıcı anlamındadır. Rahmân ve rahîm, rahmet kökünden türemiştir. İkisi de Allah’ın engin merhamet ve şefkatini bildirir. Ancak aralarında şöyle bir fark vardır: Rahmân ismi dünyada mü’min kâfir herkesi kuşatmışken, rahîm, sadece inananlara mahsustur. Bu bakımdan Allah, âhirette sadece mü’minlere rahmet ederek, onları cennetine koyacaktır. Rahmân ve rahîm isimleri iki türlü rahmet ifâde eder. Rahmân isminin ifâde ettiği rahmet, hiç bir şarta, kesbe ve irâdeye bağlı olmayarak bahşolunan rahmettir. Bu bütün yaratıkları kapsayan bir rahmettir. Bunda çalışan çalışmayan, itaatli suçlu, inançlı inançsız ayırımı yoktur. Rahîm isminin ifâde ettiği rahmet ise, Rahmân’ın lütfu olan rahmeti iyiye kullanarak çalışanlara bir mükâfât olmak üzere verilen rahmettir. Bu, en az bire ondur. Çalışanın samimiyetine göre yedi yüz katına ve hatta daha fazla katlara çıkabilir. Elbette çalışanla çalışmayan bir olmaz."),
  DataEsma(
      position: 4,
      name: "EL-MELİK",
      ebced: 90,
      zikirgunu0: "UTARİT",
      zikirgunu1: "ÇARŞAMABA",
      faziletUzun: "Sabah namazının ardından 121 defa Ya Melik ismini zikreden fakirlikten kurtulur. Bu ismi her gün okumaya devam edenler bazı sırlara vakıf olurlar. İlim ve marifet sahibi olurlar.",
      faziletKisa: "Emir sahibi olmak, maddi ve manevi güçlü olmak için okunur.",
      kisaAciklama: "Kainatın sahibi, mülk ve saltanatı sürekli olan.",
      uzunAciklama:
          "Görülen ve görülmeyen bütün âlemlerin, bütün kâinatın tek sahibi ve mutlak surette tek hükümdârı demektir. Kendisine ibâdet edilmeye yegâne lâyık olan O’dur. O’nun istediği olur, istemediği olmaz. O, bir şeyin olmasını isterse, sadece “ol” der, o da derhal olur. Olmasını istemediği hiçbir şey de asla varlık sahasına çıkamaz. Bütün evren, yaratılmış olan her şey, mükemmel bir düzen içerisinde işlemektedir. Asla bir başı boşluk ve düzensizlik yoktur. Bütün idâre tek bir yerden geliyor. O Allah, dünya ve âhiret hayatındaki her şeye gerçek anlamda ve kayıtsız şartsız hâkim ve mâlik olan ve dilediği gibi tasarrufta bulunandır."),
  DataEsma(
      position: 5,
      name: "EL-KUDDÛS",
      ebced: 170,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Kuddüs ismini zikreden kişi şehvetten kurtulur, ahlakı düzelir. Günde 100 defa okuyan kalbin manevi hastalıklarından kurtulup, insanlar arasında sevilen, saygı duyulan kişi olur. Vesveseden kurtulur. Şeytanın hilelerinden uzak olur.",
      faziletKisa: "Günahlardan kurtulmak ve kalp temizliği için okunur.",
      kisaAciklama: "Her türlü eksiklikten uzak olan.",
      uzunAciklama:
          "Hatadan, gafletten, âcizlikten, her türlü eksiklikten uzak, bütün kemâl sıfatları üzerinde toplamış, bütün övgülerin üstünde olan demektir. Her türlü ayıptan, kusurdan ve ihtiyaçtan uzak olan, her türlü hayır ve bereketin kaynağı olan mübarek zât demektir. Her türlü eksiklikten, lekeden, pastan, kirden son derece temiz demektir. Gördüğümüz görmediğimiz, bildiğimiz bilmediğimiz her şeyi yaratan Allah Teâlâ, kâinâtı akıllara durgunluk verecek bir düzen ile yaratmıştır."),
  DataEsma(
      position: 6,
      name: "ES-SELÂM",
      ebced: 131,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Hasta üzerine 121 veya 161 defa Ya Selam ismi okunursa hasta iyileşme gösterir. Es Selam ismini kağıda yazıp üzerinde taşıyan ve sürekli zikr eden; fenalık ve kötülüklerden emin olur. Ya Selam isminin zikrine devam eden kişi; cin, şeytan ve insanların hile ve vesveselerinden uzak olur. 66 defa bir kaba yazıp, 40 gün aç karnına bu sudan içen vesvese hastalığından kurtulur. Günde 360 defa okuyanın her duası kabul olur.",
      faziletKisa: "Korkulan her şeyden korunmak için okunur.",
      kisaAciklama: "Her tehlikeden selamete çıkaran.",
      uzunAciklama:
          "Her türlü eksiklikten, ayıptan, kusurdan, yaratılmışlara özgü değişim ve yok oluştan münezzeh ve sâlim olan; kullarını her türlü kötülüklerden, tehlikelerden selâmete çıkaran; Cennetteki kullarına selam veren demektir. Allah, gerek dünyada, gerekse âhirette tehlikeye düşen kullarını tehlikelerden kurtarıp selamete çıkarandır. Hz. Peygamber, her namazdan sonra; “Allah’ım! Sen’sin selâm ve Sen’dendir selâm!” buyurmuştur. Selâm, Esmâ-i Hüsnâ’dan biri olduğu için Müslüman olmayanlara bu lafızla selam verilmez. Müslüman olmayanlar, dua ve esenlik dileği olan “selâm”ı hak etmemişlerdir."),
  DataEsma(
      position: 7,
      name: "EL-MÜ’MİN",
      ebced: 136,
      zikirgunu0: "AY",
      zikirgunu1: "PAZARTESİ",
      faziletUzun: "Her gün sabah namazının ardından 167 defa Ya Mü’min ismini zikreden sıkıntıya düşmez. Dili, yalan ve küfürden uzaklaşır. Riyadan, zinadan, kibirden, hasedden, kötü ahlaktan uzak olur. Her gün 1132 defa Ya Mü’min ismini zikreden hastalıklardan ve sıkıntılardan kurtulur. 43 gün, 5 vakit namazların ardından, 136 defa Ya Mü’min ismini zikreden arzusuna kavuşur. Her gün okumayı adet haline getiren muhtaçlık hissetmez, kimseye muhtaç olmaz, düşman şerrinden muhafaza olur, dili kötü söz söylemez.",
      faziletKisa: "Kötü hastalıklara düşmemek için okunur.",
      kisaAciklama: "Güven veren, koruyan.",
      uzunAciklama:
          "Güven veren, va’dine güvenilen; inananları korku ve endişeden güvende kılan; mü’minlerin îmân ve samimiyetini tasdik eden; mûcizeler vermek suretiyle Peygamberlerinin doğruluğunu isbatlayan; kendisine sığınanları koruyan, emniyetle rahatlandıran demektir.Allah’ın kullarına en büyük nimetlerinden biri, îmândır. Diğeri, emniyettir. İnsan; canı, malı, ırzı, namusu için her zaman bir endişe ve korku içinde kalsaydı, bu ne büyük bir azap olurdu. Bu isim bir kulda tecellî edince, o kulun kalbine imân iyice yerleşir. O, güvenilir biri olur. Allah Teâlâ, mü’min isminin bir tecellisi olarak inananları korkulardan güvende kılıyor."),
  DataEsma(
      position: 8,
      name: "EL-MÜHEYMİN",
      ebced: 145,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Müheymin zikrine devam eden unutkanlıktan kurtulur. Bu zikre bir Ulema ile devam eden gizli sırlara vakıf olur. Yatsı namazının ardından 145 defa okuyup konuşmadan, sağ tarafına yatıp uyuyana rüyasında olacak hadiselerden haber verilir. Günde 100 defa tenha bir yerde okuyanın kalbi nurlanır. Günde 145 defa okuyan bela, musibet ve düşman şerrinden korunur. İlim ve imanı artar. Yazıp üzerinde taşıyanın rızkı ve malı artar. Allah’ın himayesinde olur.",
      faziletKisa: "İnsanların düşüncelerini anlar korunur.",
      kisaAciklama: "Her şeyi gören gözeten.",
      uzunAciklama:
          "Kâinatın bütün işlerini gözetleyip yöneten; bütün yaratıklarını gözetip koruyan; korkulardan emin kılan demektir. Yine kullarına asla zulmetmeyen; her söylediği ve yaptığına güvenilen; bütün kullarını hükmü altına alan; olup biten her şeyden haberdâr olan ve Peygamberi’ne indirdiği vahyin doğruluğuna tanıklık eden; kullarını dâimâ gözetim altında bulunduran; mü’minlere güven, sevgi ve huzur veren demektir."),
  DataEsma(
      position: 9,
      name: "EL-AZİZ",
      ebced: 94,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Aziz ismini zikreden kişi, kendini insanlara sevdirir. İşi ve istekleri geri çevrilmez. Hem insanlara, hemde ruhanilere karşı sözü geçen, itibar sahibi bir kişi olur. Ya Aziz ismi 7 gün düşmanının helakı niyetiyle okunursa, kişinin düşmanı helak olur. 40 gün sabah namazından sonra 40 defa okuyan fakirlikten kurtulur. Kimseye muhtaç olmaz. Hergün evden çıkarken, 94 defa Ya Aziz ismini zikreden dünya ve ahirette bahtiyar olur.",
      faziletKisa: " Düşmanlara galip gelmek için okunur.",
      kisaAciklama: "İzzet sahibi, her şeyin galibi.",
      uzunAciklama:
          "Yenilmesi mümkün olmayan gâlip; dengi ve benzeri bulunmayacak şekilde değerli ve şerefli; güçlü ve yenilmez demektir. Allah Teâlâ yegâne güç ve kuvvet sahibi olan mutlak gâliptir. O’nu âciz bırakacak hiç bir güç yoktur. Dilediğini izzetli, şerefli ve üstün kılar."),
  DataEsma(
      position: 10,
      name: "EL-CEBBAR",
      ebced: 206,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Cebbar ismini zikreden kişiye bütün insanlar itaat edeler, o kişiye kötülük yapmaya cesaret edemezler. Ya Cebbar ismi bir düşmanın helakı için 206 defa okunur. Ya Cebbar ve Zülcelali Vel İkram isimlerini beraber yazıp üzerinde taşıyan bütün insanlara güzel görünür. Her gören saygı ve sevgide bulunur.",
      faziletKisa: "istek ve arzuların olması için",
      kisaAciklama: "Kudret ve azamet sahibi.",
      uzunAciklama:
          " Dilediğini her durumda gerçekleştiren; istediğini zorla yaptırmaya muktedir olan; yaratılmışların halini iyileştiren; parçalanmış, dağılmış ve bozulmuş olanı düzeltip onaran; her şeyi tasarrufu altına alan demektir. Allah Teâlâ, kırılanları onarır, eksikleri tamamlar, her türlü perişanlıkları düzeltir, yoluna koyar. Düzeni bozulan her şeyi düzene koyar. Yaratıklarının ihtiyaçlarını giderir. Yaşama ve rızık sebeplerini sağlar. Kırılan ümitlerin canlanması, şaşırtıcı perişanlıkların iyi hale gelmesi ve yola konması için tek başvuru kaynağının Allah Teâlâ olduğunu bilmeli, yanlış yerlere başvurmamalıdır."),
  DataEsma(
      position: 11,
      name: "EL-MÜTEKEBBİR",
      ebced: 662,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Mütekebbir ismini hergün okuyan konuştuğu zaman karşısındakileri tesiri altında bırakır. Okuyanın hayır ve bereketi çoğalır. Her gün sabah namazının ardından 664 defa Ya Mütekebbir ismini zikreden itibarlı olur. Karşısındakiler ona itaat eder, sözü geçen bir kişi olur. Her gün müşteri saatinde 262 defa okuyanın bereketi artar. Kötü davranışları olan ve sürekli haram işleyen kişinin üzerine 262 defa okunursa o kişi davranışlarını düzeltir.",
      faziletKisa: "İzzete ve refaha nail olmak için okunur.",
      kisaAciklama: "Büyüklükte eşi ve benzeri olmayan.",
      uzunAciklama:
          "Her zaman ve her yerde büyüklüğünü gösteren; zât ve sıfatlarının mâhiyeti bilinemeyecek kadar ulu, yaratılmışların sıfatlarından yüce olan; azgın ve zâlim insanları mutlak gücüne boyun eğmek zorunda bırakan demektir. Büyüklük ve yücelik, ancak Allah’a mahsustur. İnsan çalışıp çabalamalı büyük adam olmalı, ama asla büyüklenmemelidir. Yaratılmışlar içinde ilk defa kendini büyük gören İblis olmuş ve bu durum onun lanetlenmesine, cehenneme girmesine sebep olmuştur."),
  DataEsma(
      position: 12,
      name: "EL-HÂLIK",
      ebced: 731,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Halık ismini zikredenin kalbi nurlanır. Her işte başarılı olur. Bela ve kötülüklerden korunur. İyileşmesi zor akıl hastalığı olanlar bu ismi yazıp taşımaları halinde faydasını görürler. Çözülmesi zor olan bir işi olan kişi; kıbleye yönelip 5115 defa Ya Halık ismini zikredip, işinin çözülmesi için dua ederse işi halolur.",
      faziletKisa: "İşlerde üzüntüden ve sıkıntıdan kurtulmak için okunur.",
      kisaAciklama: "Yaratan.",
      uzunAciklama:
          "Her şeyi yaratan, yoktan var eden demektir. Allah Teâlâ, eşyayı, her hangi bir örneği ve benzeri olmadan yaratandır. Yarattığı her şeyi bütün ayrıntılarıyla bilir. Her şeyin varlığını, varlığı boyunca görüp geçireceği halleri bilir, olayları tayin ve tesbit eder, ona göre yaratır. Demek ki hâlık isminin iki anlamı vardır: birincisi; bir şeyin nasıl olacağını tayin ve tesbit etmek, ikincisi, o takdire uygun olarak o şeyi yaratmak, var etmek. Allah Teâlâ, her şeyi ezelde takdir etmiş, takdir ettiklerinin zamanı gelince bunları yaratmış, varlık sahasına çıkarmıştır. O’nun ilim, irâde, takdir ve yaratmasından hiç bir şey uzak kalamaz."),
  DataEsma(
      position: 13,
      name: "EL-BARİ’",
      ebced: 213,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Bari’ ismini 7gün 100defa okuyan selamete erer ve afetlerden korunur. Günde 210 defa şems saatinde okuyan; düşmanlarını yener, feraha erer ve zihni, aklı gelişir. En az bir sene okumaya devam eden şifa verir. Şifacı olur. Ağır işler kolaylaşır. Ya Bari’ ismini 45360 defa abdestli ve kıbleye yönelerek okuyan; ardından isteği doğrultusunda dua ederse isteği gerçekleşir, duası kabul görür. Başı ağrıyan kişi El Bari’ ismini gümüşe yazıp başında taşırsa baş ağrısından kurtulur.",
      faziletKisa: "İşinde Başarılı olur, şöhret bulur.",
      kisaAciklama: "Her şeyi uyumlu ve kusursuz yaratan.",
      uzunAciklama:
          "Bir örneği ve maddesi olmaksızın yaratan; evrenin bütün parçalarını âhenkli ve düzenli olarak meydana getiren demektir. Allah Teâlâ, zât ve sıfatları bakımından yaratılmışlara asla benzemez. Yarattığı her şeyi hiç bir modele bağlı kalmaksızın yarattığı gibi, tam bir uygunluk ve kusursuzluk halinde yaratmıştır. Bir kulda bu isim tecellî edince, o kul yaptığı her şeyi adâletle, hakkâniyetle ve sağlam yapar."),
  DataEsma(
      position: 14,
      name: "EL-MUSAVVİR",
      ebced: 336,
      zikirgunu0: "AY",
      zikirgunu1: "PAZARTESİ",
      faziletUzun: "Rabbine dua edip yalnızca Rabbinden isteklerde bulunan kişiler akşam namazını kıldıktan sonra 21 defa 'Ya Musavvir' zikri yapmalıdır. Sabahları seher vaktinde her gün 'Ya Musavvir' zikrine 336 kere tekrarlamasıyla evlenmek isteyenlere hayırlı bir kısmet çıkacaktır. Yatmadan önce 336 kez 'Ya Musavvir' esmasının okunmasıyla ruhani varlıklar o kişiye görünecektir. Esmayı her gün zikreden kişiler zikir sayısını tamamladıklarında maddi ve manevi açıdan rahatlığa kavuşmaktadır. Tıp açısından çocuğu olmayan kişiler yedi gün oruç tutmalı ve akşam namazından sonra 21 defa El-Musavvır zikretmelidir. Rüya da görmek istenen biri için 'Ya Musavvir' 1000 defa zikredilmelidir.",
      faziletKisa: "Maksat ve merama ulaşmak için",
      kisaAciklama: "Varlıklara şekillerini veren.",
      uzunAciklama:
          "Varlıkları çeşitli şekillerde yaratan; yarattığı her varlığa ayrı bir şekil ve husûsiyet veren demektir. Hâlik, bâri’ ve musavvir isimlerinin üçü de yaratıcı anlamındadır. Bunlardan hâlik; bir örneği, eşi, benzeri olmaksızın ilk defa yaratan demektir. Bâri’; yarattığı şeyi düzgün yaratan, yarattığı canlıları, organları yerli yerinde, uyumlu yaratan demektir. Musavvir de; yarattığı her şeye ayrı bir şekil, biçim ve husûsiyet veren demektir. Yeryüzünde bulunan milyarlarca insanın her bir organının bir diğerine benzemeyişi, Allah’ın yaratıcılığının mükemmelliğine delildir. Bu isimden nasip alan kullar, Allah’ın yarattığı her şeye hayranlıkla ve ibretle bakarlar."),
  DataEsma(
      position: 15,
      name: "EL-ĞAFFAR",
      ebced: 1281,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Gaffar zikrine devam eden günahlarından, hata ve isyanlarından mağfiret bulur. Affolunur. Hasımlarının gözünde görünmez olur. Kavga ve savaş durumunda düşmanları tarafından görülemez. Gaffar ismini zikreden Allah’dan merhamet istemiş olur. Günde 1200 defa okuyan maddi ve manevi halini düzeltir. Gizli şeylerin esrarına vakıf olur. Sinirlenip herşeye parlayan kişiler bu ismi okursa öfkeleri yatışır. Kurşun levha üzerine yazıp üzerinde taşıyan zalimlerin şerrinden korunur. (Settar ayıpları günahları örten demektir o da esmaul husna da el-gaffar olarak geçmektedir.)",
      faziletKisa: "Bağışlanmak ve günahlardan korunmak için okunur.",
      kisaAciklama: "Çok mağfiret eden.",
      uzunAciklama:
          "Dâimâ affeden; kullarının günahlarını örten, ayıp ve kusurlarını bağışlayan; tekrarlanan günahları bağışlayan; mağfireti, bağışlaması sonsuz olan demektir. Mânevî kirlerden, günahlardan temizlenmek için Allah Teâlâ’ya istiğfar etmeli, mağfiret ve bağışlanma dilemeliyiz."),
  DataEsma(
      position: 16,
      name: "EL-KAHHAR",
      ebced: 306,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Kahhar ismi; düşmanı kahretmek ve düşmanı helak etmek gibi bir tesire sahiptir. Ya Kahhar ismini her gün okuyanların kalbinde dünya sevgisi kalmaz. Nefsine yenik düşmez. Düşmanlarını hezimete uğratır. Düşmanına karşı beddua da bulunsa düşmanı helak olur. Şehvet ve hırstan kurtulur.",
      faziletKisa: "Zalimleri kahretmek için",
      kisaAciklama: "Her şeye hakim ve galip olan.",
      uzunAciklama:
          "Yenilmeyen, yegane gâlip demektir. Allah Teâlâ, her şeye, her istediğini yapacak şekilde gâlip ve hâkimdir. Kuvvet ve kudretiyle her şeyi içinden ve dışından kuşatmıştır. O’na karşı her şeyin boynu büküktür. Dilediğini istediği anda yok ve helak eder."),
  DataEsma(
      position: 17,
      name: "EL-VEHHÂB",
      ebced: 14,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Vehhab ismini sürekli zikreden kişinin rızkı artar, maddi sıkıntılarından kurtulup, refaha erer. Mahlukata karşı güçlü ve heybetli görünür. Dua edilirken 7defa zikr olunursa duanın kabulune vesile olur. Zeka ve anlama güçlüğü olanlara yazılarak içilirse faydası olur.",
      faziletKisa: "Sıkıntısız borçsuz bir hayat için okunur.",
      kisaAciklama: "Karşılıksız hibeler veren.",
      uzunAciklama:
          "Karşılık beklemeden bol bol veren; hibesi ve lütfu çok olan demektir. Allah Teâlâ, bağışı çok olandır, karşılıksız verendir, nimetlerinin ardı arkası kesilmeyendir. İnanan inanmayan ayırımı yapmaksızın bütün kullarına nimetlerini bol bol verendir. Rahmeti gereği lütfu bol olan ve hayırlı işlerde başarıya ulaştırandır."),
  DataEsma(
      position: 18,
      name: "ER-REZZAK",
      ebced: 308,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Her sabah namazından sonra 308 defa Ya Rezzak ismini zikredenin rızkı artar, maddi sıkıntıları sona erer. Aç karnına günde 20 defa okuyanın zekası ve zihni açılır. İşini gördüreceği kişinin yüzüne 26 defa okunursa işi görülür. Kötülüklerden ve fitnelerden korunmak için sabah namazı vakti girmeden evin dört tarafına onar defa Ya Rezzak ismi okunarak üflenir. Ya Fettah Ya Rezzak isimlerini hergün beraber okuyana; kapalı kapılar açılır, maddi sıkıntıya uğramaz, rızkı artar.",
      faziletKisa: "Bol rızıklı ömür için okunur.",
      kisaAciklama: "Rızkını veren.",
      uzunAciklama:
          "Bedenlerin ve ruhların gıdasını, bütün yaratıklarının rızkını yaratıp veren demektir. Allah Teâlâ, yarattığı bütün yaratıklarının rızkına kefildir. Yerde, gökte, yer altında, denizde vb. nerede canlı varsa hepsinin rızkını yaratan Allah Teâlâ’dır. Hepsinin rızkını tam vaktinde ve unutmadan verir. Ancak insanlara, yarattığı rızıkları meşrû yoldan arayıp bulmalarını emretmiştir. Bu isimden nasip alan kul, rızkın değil, Rezzâk’ın peşinden koşar. Her nimette O’nu hatırlar. Allah’ın cömertliğine hayran kalır."),
  DataEsma(
      position: 19,
      name: "EL-FETTÂH",
      ebced: 489,
      zikirgunu0: "UTARİT",
      zikirgunu1: "ÇARŞAMBA",
      faziletUzun: "Ya Fettah isminin zikrine devam edene Allah hayır ve bereket ihsan eder. Darlık ve sıkıntı çekmez. Okuyanın kalbi nurlanır, işleri kolaylaşır. Makam ve mertebesi yükselir, kimseye muhtaç olmaz. Sabah namazlarının ardından sağ elini kalbine koyarak 71 defa okuyanın kalbi temizlenir. Yatarken okuyana rüyasında bilmediği şeyler gösterilir. Zor bir durumdan kurtuluşa ermek için niyet ederek utarit saatinde 489 defa okunur. Düşmanının dost olması niyetiylede utarit saatinde 489 defa okunmaya devam edilirse düşmanı dost olur.",
      faziletKisa: "Maddi manevi hayırlar için okunur.",
      kisaAciklama: "Darlıktan kurtaran.",
      uzunAciklama:
          "İyilik kapılarını açan; hakemlik yapan; bütün anlaşmazlıklarda hakemlik yaparak mutlak adâleti gerçekleştiren; zulme uğrayanlara yardım eden; mü’min kullarını zafere ulaştıran; mü’minlere mânevî kapıları açıp kalplerden kederleri gideren; her derde çare bulan; her türlü engelleri kaldıran demektir. Allah Teâlâ, yürekten, tasaları, kederleri giderendir. İnsanı sıkıntılardan kurtarıp göğsüne genişlik verendir. Anlaşılması zor ilimlerin üzerindeki zorluğu gidererek anlaşılmasını kolaylaştırandır. Allah, insana hidâyet yollarını açar."),
  DataEsma(
      position: 20,
      name: "EL-ALİM",
      ebced: 150,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Alim zikrine devam eden gizli sırlara vakıf olur. Herşey ona beyan olur. Okuyanın ilmi artar, hikmetli konuşur ve yüce makamlara erişir. El Alim ismini yazıp suda silip içenin anlayışı ve zekası artar.",
      faziletKisa: "ilim zenginliği için okunur.",
      kisaAciklama: "Her şeyi en küçük detaylarını bilen.",
      uzunAciklama:
          "Hakkıyla bilen demektir. Allah Teâlâ, zaman ve yer kaydı olmaksızın büyük küçük, gizli açık her şeyi bilendir. Olmuşu, olanı, olacağı en mükemmel bir şekilde bilir. Hiç bir şey O’nun bilgisi dışına çıkamaz. O’nun bilemeyeceği bir şey düşünmek mümkün değildir."),
  DataEsma(
      position: 21,
      name: "EL-KÂBİD",
      ebced: 903,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Kabid ismini okumaya devam eden kişi heybetlilik ve celallik kazanır. Kimse düşmanlık etmeye, hakkında dedikodu yapmaya cesaret edemez. Okuyan kötü huylarından kurtulur. Düşman şerrinden korunmak için 903 defa okunur. İki ay günde 10000 defa okuyana bazı sır perdeleri açılır.",
      faziletKisa: "Zalimin zülmünden kurtulmak için",
      kisaAciklama: "Dilediğine darlık veren.",
      uzunAciklama:
          "Rızkı daraltan; canlıların ruhlarını alıp hayatlarına son veren demektir. Allah Teâlâ, istediğini sıkar, daraltır; istediğini genişletir. İstediğinden verdiği zenginliği, çoluk çocuğu, hayat zevkini, gönül ferahlığını alıverir. ihsânettiği şeyleri daraltır, azaltır. Güneşin doğmasıyla karanlığı giderir. Kuşlara gökyüzünde uçma imkânı verir, onları düşmekten korur. Bu ismi “Bâsıt” ismiyle beraber değerlendirmelidir."),
  DataEsma(
      position: 22,
      name: "EL-BÂSIT",
      ebced: 72,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Basıt ismini zikreden kişi korktuğu şeylerden emin ve güven içinde olur. Kalbindeki korku ve endişeler gider. Kalbi geniş olur. Keyfi ve neşesi artar. Sıkıntılarından kurtulur. Rızkı ve itibarı artar. Kalp gözü açılır. Hergün sabah namazından sonra 72 defa Ya Basıt ismini zikredenin rızkı bollaşır.",
      faziletKisa: "İşlerin büyümesi mal ve paranın bereketi için okunur.",
      kisaAciklama: "Dilediğine bolluk veren.",
      uzunAciklama:
          "Rızkı genişleten; ruhları bedenlerine dağıtan demektir. Allah Teâlâ, kulunu darlıktan çıkaran, sıkıntıdan kurtarandır. İlâhî imtihanın gerçekleşmesi için bazan sıkar, bazan genişletir. Bazan darlık, sıkıntı verir. Bazan bolluk, rahatlık, huzur verir. Bu ismi, “Kâbıd” ismiyle beraber değerlendirmelidir."),
  DataEsma(
      position: 23,
      name: "EL-HÂFİD",
      ebced: 1481,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Hafıd ismini zikreden; korku, telaş, kötülük ve fenalıklardan emin olur ve korunur. Okuyana düşman saldıramaz. Cin, şeytan ve insan şerrinden korunur. Bu isim; korunması için, neye okunursa, o şey muhafaza olur, korunur.",
      faziletKisa: "Kötüden ve belalardan korunmak için okunur.",
      kisaAciklama: "Dereceleri alçaltan",
      uzunAciklama:
          "Alçaltan; zillete düşüren; yukarıdan aşağıya indiren demektir. Allah Teâlâ, kâfirleri, zâlimleri, zorbaları alçaltır; mü’minleri, dostlarını yükseltir. İstediği kulunu yukarıdan aşağıya atıverir. En yüksek mertebelerden en aşağı mertebelere indiriverir. Allah’ın düşürdüğünü hiç kimse yükseltemez, yükselttiğini de hiç kimse alçaltamaz. Bu ismi “Râfi’” ismiyle beraber değerlendirmelidir."),
  DataEsma(
      position: 24,
      name: "ER-RÂFİ’",
      ebced: 351,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Rafi ismini zikreden her türlü hayırlara vesile olur. Rızkı ve derecesi artar. İnsanlar arasında yüksek mertebelere ulaşır. Düşmanlarının kalbinde korku ve ürperti olur. Fakirlikten ve zalim şerrinden muhafaza olur.",
      faziletKisa: "İnsanlar arasında ve işinde yükselmek için okunur.",
      kisaAciklama: "Şeref vererek yükselten.",
      uzunAciklama:
          "Yücelten, yükselten, yukarı kaldıran, şeref veren demektir. Allah Teâlâ, dilediği kuluna şeref bahşederek yükseltir, diğer kullarından üstün kılar. Dilediğini zengin kılar, şerefli kılar, saygıdeğer kılar. Dilediğine îmân bahşeder, sâlih ameller işlemesine ve cennetine girmesine imkân verir. Bu ismi, “Hâfid” ismiyle beraber değerlendirmelidir. Râfi’; dostlarının tâat ve amellerini kabul edip kendisine yaklaştıran, dünyada şerefli kılan demektir. Hâfid de; kendisine itâat etmeyenleri kendisinden uzaklaştıran, mertebelerini düşüren demektir."),
  DataEsma(
      position: 25,
      name: "EL-MUİZZ",
      ebced: 117,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Muizz zikrine devam eden kişi aziz olur. Gücü, kuvveti artar. Kadri yücelir. Mahlukata karşı heybetli görünür. Kimseden korkmaz.",
      faziletKisa: "Fakir ve zelillikten kurtulmak için okunur.",
      kisaAciklama: "Dilediğini aziz eden.",
      uzunAciklama:
          "Üstün kılan, izzet ve şeref veren; mülkü dilediğine veren demektir. Allah Teâlâ, kendisine inananları yükseltir, şereflendirir, başkalarına üstün kılar. Îmân ehli, Allah’ın azîz ve değerli kıldığı kimselerdir. “Muizz” ismini “Müzill” ismi ile beraber değerlendirmelidir."),
  DataEsma(
      position: 26,
      name: "EL-MÜZİLL",
      ebced: 770,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Muzill ismini zikreden kişiye, istediği düşmanını Allah zelil kılar. Düşman ve zalim şerrinden emin olur, korunur. Düşmanını hezimete uğratır.",
      faziletKisa: "Düşmanları zelil etmek için",
      kisaAciklama: "Dilediğini zillete düşüren.",
      uzunAciklama:
          "Zillete düşüren, hor ve hakir kılan, rezil ve perişan eden, alçaltan demektir. Gönülleri dünya hırsı ile yanıp tutuşan kişiler, Allah’ın zelil kıldıklarıdır. Bunların şiarı dünya çıkarı için nefsini alçaltmaktır. Bunlar yarın Allah’ın huzuruna yüzleri kararmış olarak çıkacaklardır. “Müzill” ismini, “Muizz” ismi ile beraber değerlendirmelidir."),
  DataEsma(
      position: 27,
      name: "ES-SEMİ’",
      ebced: 180,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Semi ismini zikredenin duaları kabul olur. 7 gün oruç tutup, halvete girerek Ya Semi ismini zikreden ulvi ruhların sesini işitir.",
      faziletKisa: "Duaların kabulu için okunur.",
      kisaAciklama: "Her şeyi işiten.",
      uzunAciklama:
          "Sonsuz işiten, her türlü kısıtlamadan yüce olarak gizli açık her şeyi işiten; işitilecek şeyler kendisine gizli kalmayan; dilek, dua ve yakarışları kabul eden demektir. Allah Teâlâ, ister açık, ister gizli bütün sesleri, fısıltıları işitir. Kendisine içinden hamd edenin hamdini işiterek onu mükâfâtlandırır. Dua edenlerin dualarını kabul eder. Allah’ın işitmesi kullarınki gibi kulak ve ses gibi bazı vasıtalarla değildir."),
  DataEsma(
      position: 28,
      name: "EL-BASÎR",
      ebced: 302,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Basır ismini zikredenin dünya ve ahiret korkuları kalmaz. Basiret gözü açılır. Tüm kötülüklerden korunur. İstek ve arzuları gerçekleşir. Ya Basır ismini her sabah 302 defa zikreden gizli husus ve hadiseleri öğrenir. Ya Allahü Ya Basır isimlerini zikredenin içi temizlenir. Allah’ın rahmetini kazanır. Gözleri nurlanır.",
      faziletKisa: "Acziyetin kalkması için okunur.",
      kisaAciklama: "Her şeyi en iyi gören.",
      uzunAciklama:
          "Sonsuz görücü; her şeyi gören, bilen; kendisinden hiç bir şey saklanamayan demektir. Allah Teâlâ’nın görmesi de işitmesi ve diğer isim ve sıfatları gibi sonsuzdur. Her hangi bir organ ve vasıta ile değildir. Görme konusu olan her şeyi görür. Açıkta olanları gördüğü gibi gizli olanları da görür. Dışımızı gördüğü gibi içimizi de görür. O hâlde devamlı bir şekilde Rabbimiz tarafından görüldüğümüzü ve gözetlendiğimizi unutmamamız, buna göre söz ve davranışlarımıza dikkat etmemiz gerekir."),
  DataEsma(
      position: 29,
      name: "EL-HAKEM",
      ebced: 68,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Hakem ismini zikredenin içi, alemin sırlarıyla dolar. Sözü geçerlive tesirli olur. Allah katında mertebesi yükselir. Eşyaların sırrına vakıf olur. Anlama ve kavrama gücü artar.",
      faziletKisa: "Haklı davasını kazanması için okunur.",
      kisaAciklama: "Mutlak hakim olan. Hikmetle hükmeden.",
      uzunAciklama:
          "Hükmeden, hakkı yerine getiren; hüküm yetkisi kendisine ait olan; son hükmü verecek olan demektir. Allah Teâlâ, hâkimdir. Her şeyin hükmünü O verir. Verdiği hükmü tamamiyle yerine getirir. O’nun hükmünü engelleyecek, bozacak, değiştirecek, geri bıraktıracak hiç kimse yoktur. Kıyâmet gününde Allah Teâlâ hükmünü verecek, adâlet tam olarak gerçekleşecek ve herkes hak ettiğinin karşılığını tam olarak alacaktır. Hiç kimseye en küçük bir haksızlık yapılmayacaktır."),
  DataEsma(
      position: 30,
      name: "EL-ADL",
      ebced: 104,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Adl ismini zikredenin maddi ve manevi hali düzelir. Hakim ve hükümet görevlileri her gün sabahları 104 defa Ya Adl ismini zikrederlerse, adalet üzere hareket ederler, adaletten ayrılmazlar. Gece yarısından sonra 104 defa Ya Adl ismi zikredildikten sonra bir zalime beddua edilirse; o zalim perişan olur.",
      faziletKisa: "Adaletli olmak için",
      kisaAciklama: "Mutlak adil olan.",
      uzunAciklama:
          "Mutlak adâlet sahibi, çok adâletli, asla zulmetmeyen; her şeyi yerli yerine koyan demektir. Allah Teâlâ, çok adâletlidir. Hiç kimseye en küçük bir haksızlık yapmaz. Herkes neyi hak ettiyse, herkese hakkını tam olarak verir. Yaptığı her şey, akla, mantığa, hikmet ve maslahata uygundur. Bu isimden nasip alan kul, zulmün her çeşidinden kaçınır; kendi aleyhine bile olsa adâletten ayrılmaz."),
  DataEsma(
      position: 31,
      name: "EL-LÂTİF",
      ebced: 129,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Latif ismi; insana her hususta fayda veren, havassı en çok olan isimlerden biridir. Ya Latif ismini zikreden huzura kavuşur, her şeyde başarılı olur. Maddi durumu düzelir. Hasta olan iyileşir. Sıkıntı ve bunalımdan kurtulur. Arzu ve isteklerine kavuşur. Günde 16641 defa okunması tavsiye edilmiştir.",
      faziletKisa: "Dileklerin olması, kısmet ve rızık için Okunur.",
      kisaAciklama: "Bütün incelikleri bilen.",
      uzunAciklama:
          "Yaratılmışların ihtiyaçlarını en ince ayrıntıya varıncaya kadar bilip sezilmez yollarla karşılayan; kullarına yumuşaklıkla, lütuf ve ihsânıyla muâmele eden demektir. Allah Teâlâ, kullarına iyilik ve merhamet edendir. Fiillerini yumuşaklıkla gerçekleştirendir. Sonsuz lütuf ve kerem sahibidir. Kendisine gizli olan hiç bir şey yoktur."),
  DataEsma(
      position: 32,
      name: "EL-HABÎR",
      ebced: 812,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Habir ismini zikredende ruhaniyet kesbeder, eşyanın sırrına vakıf olur. Kötü ahlak ve zalim şerrinden kurtulur. Rüyasında istediği şey hakkında bilgi alır. 40 gün 7000 defa okuyan bu ismin hadimi ile görüşür.",
      faziletKisa: "Hafıza ve idrakin genişlemesi için",
      kisaAciklama: "Her şeyden haberdar.",
      uzunAciklama:
          "Her şeyi bilen, her şeyin iç yüzünden, gizli taraflarından haberdâr olan demektir. Allah Teâlâ, yerde ve gökte, bütün evrende olan gizli açık her şeyden haberdârdır. O’nun bilemeyeceği bir şey düşünmek mümkün değildir. Bu bakımdan yaptığımız her şeyi Allah’ın bildiğini düşünerek yapmalıyız."),
  DataEsma(
      position: 33,
      name: "EL-HALİM",
      ebced: 88,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Halim ismini zikreden arifler zümresinden olur. Merhametli ve sözü geçen bir kişi haline gelir. Dünyayı bırakıp, tâata yönelir. Sinirli ve asabi olan kişiler okursa durumları düzelir.",
      faziletKisa: "Ahlak ve hılim / huy güzelliği için okunur.",
      kisaAciklama: "Cezada, acele etmeyen.",
      uzunAciklama:
          "Suçluların cezasını vermeye gücü yettiği hâlde cezalandırmayıp onlar hakkında yumuşak davranan, cezalarını geriye bırakan; acele ve kızgınlıkla muâmele etmeyen demektir. Allah Teâlâ, günahları yüzünden kullarına olan lütuf ve ihsânını esirgemez. İyi olsun kötü olsun bütün kullarını rızıklandırır; belâ ve âfetlerden korur. Acelecilikle ve kızgınlıkla davranmaz. Çok yumuşak davranır. Ceza vermekte acele etmez. Süre tanır, ama ihmal etmez."),
  DataEsma(
      position: 34,
      name: "EL-AZİM",
      ebced: 20,
      zikirgunu0: "UTARİT",
      zikirgunu1: "ÇARŞAMBA",
      faziletUzun: "Ya Azim ismini zikreden korktuğu ve çekindiği şeylerden korunur. Hastaysa şifa bulur. İnsanlar arasında itibarlı olur, şerefi yücelir. İstek ve arzularına kavuşur. İşlerinde başarıya ulaşır. Yüksek mertebelere ulaşır.",
      faziletKisa: "Sözünün tesirli ve sayırlı olmak için",
      kisaAciklama: "Pek yüce.",
      uzunAciklama:
          "Büyük, yüce, ulu demektir. Allah Teâlâ, zât ve sıfatları bakımından en büyüktür. Mutlak ve ekmel büyüklük Allah’a mahsustur. O, hiç bir şekilde âciz bırakılmayacak olan Kâdir-i mutlaktır. Akıl, O’nun büyüklüğünü idrâkten âcizdir."),
  DataEsma(
      position: 35,
      name: "EL-ĞAFÛR",
      ebced: 1286,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Gafur ismini zikredeni Allah af ve mağfirette bulunur. Fakirlikten kurtulur. Korktuklarından emin olur, korunur. Şiddet ve öfkeli kişilere karşı Ya Gafur ismi okunursa öfkeleri yatışır. Her farz namazının ardından Ya Gafur ismini okumaya devam edene; ruhaniler gelerek isteklerini yerine getirir.",
      faziletKisa: "Günahların affı, kötü ahlakı bırakmak için okunur.",
      kisaAciklama: "Mağfireti bol.",
      uzunAciklama:
          "Günahları bağışlayan; affeden demektir. Allah Teâlâ, bağışlaması bol olandır. Kulun günahı ne kadar çok olursa olsun Allah Teâlâ, bunları meydana çıkarıp kulunu rezil ve rüsvay etmez, bunları örter ve gizler. Kulun, işlediği gü nahları ve suçları bağışlar. Sonsuz mağfiret edici ve bağışlayıcıdır. Bu isimden nasip alan kul, daima istiğfâra yönelir. Şahsına yapılan haksızlıkları bağışlar. Kin tutmaz."),
  DataEsma(
      position: 36,
      name: "EŞ-ŞEKÛR",
      ebced: 526,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Şekur ismini zikreden kişinin refahı artar, sıhhat ve huzur içinde olur. Her işinde kolaylık bulur. Kazandığını kaybetmez. Nimetleri eksilmez. Zalim ve düşman şerrinden korunur.",
      faziletKisa: "Talihin açıklığı, bol rızık için okunur.",
      kisaAciklama: "Çok sevap veren.",
      uzunAciklama:
          " Az iyiliğe çok mükâfât veren; kendi rızası için yapılan iyilikleri fazlasıyla mükâfâtlandıran demektir. Allah Teâlâ, kulların işlediği ibâdet ve iyilikleri fazlasıyla karşılayandır. Kul, Allah’ın verdiği nimetlere şükürle karşılık vermelidir. Kul şükrederse, Allah onun şükrünü karşılıksız bırakmaz, fazlasıyla mükâfâtlandırır."),
  DataEsma(
      position: 37,
      name: "EL-ALİYY",
      ebced: 110,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Aliyy ismini zikreden kişi hor görülmez, onu gören herkez sever, sayar. Sözü dinlenir. Ahlakı düzelir, hikmetli konuşur. Kısmeti açılır, kötü huylarını bırakır.",
      faziletKisa: "Zilleten kurtulmak ve ilim için",
      kisaAciklama: "Yüceler yücesi.",
      uzunAciklama:
          "Pek yüce, pek yüksek demektir. Allah Teâlâ, insan tasavvurunun tahayyül edeceği her şeyden daha büyük, daha yüce ve daha yüksektir. İzzet, şeref ve hükümranlık bakımından O’ndan daha yüce bir varlık yoktur. O’nun yüksekliği cisimlerin sahip olduğu türden değildir. Yücelik ve üstünlük bakımındandır."),
  DataEsma(
      position: 38,
      name: "EL-KEBİR",
      ebced: 232,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Kebir ismini zikredenin ilmi ve bilgisi artar. İnsanlardan hürmet görür. Onu görenler, ondan çekinir. Yüce mertebelere erer. Borçlu kişiler günde 1000 defa okurlarsa borçlarını ödemeye muvaffak olurlar. İşinden haksız yere uzaklaştırılanlar, görevlerine ve işine geri döner.",
      faziletKisa: "Hürmet görmek için okunur.",
      kisaAciklama: "Çok büyük olan.",
      uzunAciklama:
          "Büyük ve ulu demektir. Allah Teâlâ, her hususta insanların kavrayamayacağı kadar ulu ve büyüktür. Zâtının ve sıfatlarının mâhiyeti bilinemeyecek kadar uludur. Mutlak büyüktür. Kudret ve hükümranlığı sınırsızdır. Hiç bir şeye muhtaç değildir. Yaratılmışlara benzemez. O’nun büyüklüğü, mekâna bağlı bir büyüklük değildir. O, bundan münezzehtir."),
  DataEsma(
      position: 39,
      name: "EL-HAFÎZ",
      ebced: 998,
      zikirgunu0: "ZUHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Hafız ismini zikreden kişi; zalim ve kötülerin şerrinden korunur. Düşmanlarına güçlü görünür ve düşmanlarına karşı üstün olur. Bir zalime beddua ederse, bedduası gerçekleşir.",
      faziletKisa: "Nefsinin ve malının korunması için okunur.",
      kisaAciklama: "Her şeyi koruyan.",
      uzunAciklama:
          "Koruyup gözeten; kendisinden gizli hiç bir şey olmayan demektir. Allah Teâlâ, evrenin düzenini koruyup sürdürendir. Her şeyi eksiksiz kaydedip hesaba çekmek üzere koruyandır. İnsanların niyetlerini ve bütün sırlarını bilendir. İnsanların söz ve hareketlerini melekler aracılığıyla tesbit ve tescil ettirendir. Dostlarını kötülüklerden koruyandır."),
  DataEsma(
      position: 40,
      name: "EL-MUKIYT",
      ebced: 550,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Mukit ismini zikredenin rızkı artar, malı eksilmez. Açlık hissetmez. Fenalıklardan korunur, rızkı kolaylaşır, bereketi artar.",
      faziletKisa: "Muhtaç olunan şeyi kazanmak için",
      kisaAciklama: "Her yaratılmışın rızkını veren.",
      uzunAciklama:
          "Yaratılmışların her türlü gıdalarını yaratıp veren; her şeye gücü yeten ve koruyan demektir. Allah Teâlâ, bedenlerin ve ruhların gıdasını yaratıp verendir. Yarattığı bütün canlılara ne kadar ömür takdir etmişse ona göre rızıklarını da tayin ve takdir etmiştir. Herkesin rızkı bellidir. Herkes kendi rızkını yer, kimse kimsenin rızkını yemez."),
  DataEsma(
      position: 41,
      name: "EL-HASİB",
      ebced: 80,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Hasib ismini her gün zikredenin duaları kabul olur. Başkaları tarafından sevilip, sayılır. Düşman şerrinden korunur. Kötülüklerden muhafaza olur. Rızkı çoğalır.",
      faziletKisa: "Herkese karşı alnı açık olmak için okunur.",
      kisaAciklama: "Kulların hesabını gören.",
      uzunAciklama:
          "Kullarına yeten; onları hesaba çeken demektir. Allah Teâlâ, herkesin hayatı boyunca yapıp ettiklerinin bütün ayrıntılarıyla hesabını iyi bilendir. Bütün kullarını yaptıklarından dolayı veya yapmaları gerekenleri yapmadıklarından dolayı çok ayrıntılı bir şekilde hesaba çekecek ve herkesin hak ettiğini tam olarak verecektir."),
  DataEsma(
      position: 42,
      name: "EL-CELİL",
      ebced: 73,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Celil ismini zikreden insanlar arasında sevgi, saygı ve hürmet görür; heybetli ve güçlü görünür. Kimse kötü gözle bakamaz, düşmanları onu görünce korkuya kapılır. Bu ismi zikreden kişide manevi bir güç meydana gelir. Zalimleri dize getirir. Kimse kötülük yapamaz. Tehlikeli yerlerde emin olur. Okuyanın ahlakı düzelir.",
      faziletKisa: "Bir zalimi zorbayı zelil etmek için okunur.",
      kisaAciklama: "Azamet sahibi olan.",
      uzunAciklama:
          "Azamet ve ululuk sahibi demektir. Allah Teâlâ, bütün sınırlama ve benzerlikleri aşan bir yüceliğe sahiptir. Değer ve mertebece en yüce olandır. Mü’minleri yücelten, amellerini kabul edip mükâfâtlarını artırandır. O, zât, sıfat ve fiilleri itibariyle en büyüktür. O’nun büyüklüğü hacim itibariyle değildir; şân, şeref ve yücelik itibariyledir."),
  DataEsma(
      position: 43,
      name: "EL-KERİM",
      ebced: 270,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Kerim ismini zikreden kolay yoldan rızık kazanır. Hayır kapıları açılır, fakirlik çekmez. Dünya ve ahirette izzetli ve şerefli olur. Her kazancı bereketlenir.",
      faziletKisa: "Bol rızık ve kolaylıklara nail olmak için okunur.",
      kisaAciklama: "Çok ikram eden.",
      uzunAciklama:
          "İhsânı, in’âmı, lütfu, keremi bol olan, sonsuz cömert demektir. Allah Teâlâ, her türlü faziletin sahibidir. Hiç bir karşılık beklemeden verendir. Yardımı ve ikrâmı sonsuz ve sınırsızdır. Muktedirken, affedendir. Va’dini yerine getirendir. Kendisine sığınanı yüz üstü bırakmayandır. Az da olsa işlenen iyi ameli kabul eden, karşılığını fazlasıyla verendir. Bu isimden nasip alan kul, cimriliğin her çeşidinden kurtulur. Allah’ın kendisine verdiği nimetleri diğer kullarıyla paylaşmasını bilir. Şahsiyetini zedeleyecek her türlü rezillikten kurtulur."),
  DataEsma(
      position: 44,
      name: "ER-RAKÎB",
      ebced: 312,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Rakib ismini okuyanlar yitiğini bulur, başına gelecek bela ve musibetlerden korunur. Allah’ın himayesine girer. Sabah namazının ardından 612 defa Ya Rakib ismini zikreden Allah’ın himayesine girer. 40gün oruç tutup hergün 4440 defa Ya Rakib ismini okuyan bazı sırlara vakıf olur. Kalb gözü açılır, kuşların konuşmalarını anlar.",
      faziletKisa: "Her işte Allah’ın koruması altında olmak için okunur.",
      kisaAciklama: "Her an gören gözeten.",
      uzunAciklama:
          "Her şeyi gözetleyip denetleyen; kontrol eden demektir. Allah Teâlâ, yaratıklarından bir an bile gâfil değildir. Kim ne yaparsa onu görür ve bilir. Hiçbir şey Allah’tan gizli kalmaz. Bütün varlıklar üzerinde gözcüdür, gözetleyicidir. Bütün işler O’nun denetimi ve gözetimi altında meydana gelmektedir. O, bütün olan bitenlere şahittir. Herkese yaptığının karşılığını verir."),
  DataEsma(
      position: 45,
      name: "EL-MÜCİB",
      ebced: 55,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "İhlasla “Yâ Mücib” diye bir müslüman bu isme devam etse, insanlar tarafından sevilir, duası kabul olur. 55 defa okuyanın meşru duaları kabul olunur. (Allahulalem)",
      faziletKisa: "Duaların kabul olunması için okunur.",
      kisaAciklama: "Duaları kabul eden",
      uzunAciklama:
          "Kendine yalvaranların isteklerini veren; kullarının dileklerine ve dualarına karşılık veren demektir. Allah Teâlâ, kullarına, onlardan daha yakındır. Kendine yalvaranları işitir, bilir ve onların isteklerini verir. İnsanın duâya şiddetle ihtiyacı vardır. Duâ, bir bakıma ibâdettir. Duâdan mahrum kalmamak lazımdır."),
  DataEsma(
      position: 46,
      name: "EL-VÂSİ’",
      ebced: 137,
      zikirgunu0: "AY",
      zikirgunu1: "PAZARTESİ",
      faziletUzun: "Ya Vasi ismini zikreden; hırs ve sıkıntılardan kurtulur. Ahlakı güzelleşir. Rızkı bollaşır ve ömrü uzar. Zor işlerinde daima kolaylık bulur. Kin ve hased çeken kişi okumaya devam ederse durumu düzelir. İhlasla okumayı sürdürenler; bazı sırlara ererler ve manevi perdeler o kişiye kalkar.",
      faziletKisa: "Ömür uzunluğu, rızık ve sıhhat genişliği için okunur.",
      kisaAciklama: "İlmi ile her şeyi kuşatan.",
      uzunAciklama:
          "İlmi ve merhameti her şeyi kuşatan demektir. Allah Teâlâ, kullarına bolca ihsân eden, rızıklarını genişletendir. Allah ilim, lütuf ve ihsânı ile her şeyi kuşatmıştır. Nimetlerinin bir kısmı fayda sağlayan türden, diğer bir kısmı da zararları gideren türdendir."),
  DataEsma(
      position: 47,
      name: "EL-HAKÎM",
      ebced: 78,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Hakîm ismini zikreden kişi ilim ve hikmet sahibi olur. Cuma günü 6084 defa.",
      faziletKisa: "İlim ve hikmet sahibi olmak için okunur.",
      kisaAciklama: "Her işi hikmetli.",
      uzunAciklama:
          "Hikmet sahibi demektir. Allah Teâlâ, yaptığı her şeyi yerli yerince, eksiksiz ve tam yapar. En üstün bir ilim sahibidir ve yaptığı her şey mutlaka bir hikmete mebnîdir; hikmetsiz asla iş yapmaz. Bütün emirleri insanların yararına olduğu gibi bütün yasakları da insanların zararınadır."),
  DataEsma(
      position: 48,
      name: "EL-VEDÛD",
      ebced: 20,
      zikirgunu0: "AY",
      zikirgunu1: "PAZARTESİ",
      faziletUzun: "Ya Vedud ismini zikreden kişiyi bütün insanlar sever, sayar, hürmet görür. Okumaya devam eden kişi başkalarına tesir eder ve karşısındakini hükmü altına alır. Kalbi nurlanır, huzura kavuşur. Günde 270 defa Ya Vedud ismini zikreden borçlarından ve fakirlikten kurtulur.",
      faziletKisa: "Herkesin sevgisini kazanmak",
      kisaAciklama: "Kullarını seven, sevilmeye en layık olan.",
      uzunAciklama:
          "Çok seven ve çok sevilen; sevilmeye lâyık olan demektir. Allah Teâlâ, sâlih kullarını sever, sâlih kulları da Allah’ı sever. Sâlih kullarından râzıdır. Allah yaratılmış bütün varlıkların hayrını ister. Bu nedenle onlara ihsân ve ikrâmlarda bulunur. Sevilmeye en çok lâyık olan da O’dur. Her mü’minin hedefi Allah dostluğunu kazanabilmek olmalıdır. Bunun için her türlü fedakârlığa katlanmalıdır. Bu isimden nasip alan kul, hem Allah adına herkesi, her şeyi sever; hem de herkes tarafından sevilir."),
  DataEsma(
      position: 49,
      name: "EL-MECÎD",
      ebced: 57,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Mecid ismini sürekli zikredene şeytan yaklaşıp vesvese veremez. İnsanlar arasında izzeti ve sevgisi artar. Fakirlikten kurtulur, rızkı çoğalır. Arabi ayın ortasında oruç tutup, iftar zamanı Ya Mecid ismini zikreden; maddi ve manevi hastalıklardan şifaya kavuşur,Sedef hastalığından kurtulur.",
      faziletKisa: "İzzet ve şerefin artması için okunur.",
      kisaAciklama: "Övgüye layık bulunan.",
      uzunAciklama:
          "Şânı büyük, yüksek; lütuf ve ikrâmı bol demektir. Allah Teâlâ, her türlü eksikliklerden yücedir. Şânı büyüktür. Lütuf ve keremi çoktur. Her türlü övgüye lâyıktır. Affı, ihsânı, rahmeti ve yardımı sonsuzdur. Nimetleri saymakla bitmez."),
  DataEsma(
      position: 50,
      name: "EL-BÂİS",
      ebced: 573,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Bâ’is ismini zikreden kişiden gaflet ve şiddet kalkar. Okuyanda Allah korkusu meydana gelir. İbadet ve taatını isteyerek, severek yapar. Dert ve sıkıntılarından kurtulup, huzura erer. Düşman ve zalimlerin şerrinden kurtulmak için günde 573 defa Ya Bais, zikredilir. İftiradan kurtulmak için 7073 defa okunur.",
      faziletKisa: "Kuvvetli irade ve alacaklarını almak için okunur.",
      kisaAciklama: "Ölüleri dirilten.",
      uzunAciklama:
          "Ölüleri dirilten, Peygamber gönderen demektir. Allah Teâlâ, öldükten sonra diriltendir. İnsanlar ölüp toprak olduktan sonra onları diriltecek, kabirlerinden çıkaracak, mahşerde toplayacak, çok ayrıntılı bir şekilde hesaba çekecektir. Allah Teâlâ, aynı zamanda insanlara doğru yolu göstermek üzere Peygamberler gönderendir. Peygamberlere uyanlar kurtulacak, uymayanlar azâbı hak edeceklerdir."),
  DataEsma(
      position: 51,
      name: "EŞ-ŞEHÎD",
      ebced: 319,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Asi olan insanlar için okunursa asilikleri geçer. Ana-babaya karşı gelen kişinin veya kocasına karşı isyan eden kadının başından tutularak Ya Şehid ismi okunursa isyanları ve asilikleri geçer. Veya alın bölgesinden bir kıl koparılıp, kılın üzerine 1000 defa Ya Şehid ismi okunup, Allah’dan itaatli olması istenirse; o kişi itaatkar olur. Ya Şehid ismini zikreden kişi; nefis ahlakının kötülüklerinden kendini korumaya alır. Her gün sabah namazlarının ardından 122 defa Ya Şehid ismini zikreden şahadet nimetine kavuşur. İftiraya uğrayan Ya Allah Ya Şehid isimlerini gece yarısında 329 defa okumaya devam ederse iftiradan kurtulur. Zulme uğrayan kişi 1ay süreyle 319 defa Ya Şehid ismini zikredip, o kişinin ıslahı için dua ederse zulumden kurtulur; zulmedende cezasını bulur.",
      faziletKisa: "Şehid olmak, heybetli olmak için okunur.",
      kisaAciklama: "Her yerde her zaman hazır olan.",
      uzunAciklama:
          "Her zaman, her yerde hazır olan; her şeye şâhit olan; kendisine hiçbir şey gizli olmayan demektir. Allah Teâlâ, her şeyi bilendir. İlminden hiç bir şey gizli olmayandır. Allah, açıkta olanları da bilir, gizli olanları da bilir. O, her şeye şâhittir. Âhirette herkese halini bildirecektir."),
  DataEsma(
      position: 52,
      name: "EL-HAKK",
      ebced: 108,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Hakk ismini zikreden kişi gizli sırlara vakıf olur. Halk arasında sözü geçen, dinlenen bir kişi olur. Kulluk görevlerini yerine getirmede zorlanmaz. Ahlakı ve durumu düzelir. Batıldan uzak olur.",
      faziletKisa: "Sağlam bir imana ve doğru bir ibadet hayatına sahip olmak, başladığı işin sonunun gelmesi.",
      kisaAciklama: "Var olan, hakkı gösteren.",
      uzunAciklama:
          "Varlığı gerçek olan, varlığı hiç değişmeden duran; varlığı ve ilâhlığı kesin olan, hükmünün gereğini yerine getiren demektir. Allah Teâlâ, varlığı ve ilâhlığı kesin olan, inkârı mümkün olmayandır. O’nun zâtı yokluğu kabul etmediği gibi bir değişikliği de kabul etmez. Hükmünün gereğini yerine getirendir. Ezelî ve ebedî olandır. Değişmeksizin varlığı devam edendir. Varlığı fiilen gerçek olandır yani sadece zihinde değil, zihnin dışında da var olandır."),
  DataEsma(
      position: 53,
      name: "EL-VEKİL",
      ebced: 66,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Vekil ismini zikreden musibetlerden korunur. Rüzgar ve gök gürültüsü korkularından emin olur. Rızık kapıları açılır. Hergün sabah vakti 66 defa Ya Vekil ismini zikredenin rızkı artar. Düşman üzerine zöhre saatinde 66 defa Ya Vekil ismini 66 defa okuyarak beddua edilirse düşman hezimete uğrar.",
      faziletKisa: "Allah’tan her türlü yardımı görmek için okunur.",
      kisaAciklama: "Kendisine tevekkül edenlerin her işini yoluna koyan.",
      uzunAciklama:
          "İşlerini kendisine bırakanların işlerini en mükemmel bir şekilde yapan; kendisine güvenilip dayanılan demektir. Allah Teâlâ, her bakımdan insanın güvenip dayanacağı varlıktır. En güzel vekildir, en büyük vekildir. Yarattığı bütün varlıkların işlerini idare edendir. Allah Teâlâ, elinden geleni yaptıktan sonra işini Allah’a havale edeni, mükâfâtlandırır."),
  DataEsma(
      position: 54,
      name: "EL-KAVİYY",
      ebced: 117,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Kaviyy ismini zikredenin himmeti artar. Kuvvetlenir. Okuyan yolculuk sırasındaki kaza, bela ve hastalıklardan korunur. Günde 126 defa Ya Kaviyy ismini zikredenin kalp ve ruh kuvveti artar. Ağır bir yük kaldırırken Ya Kaviyy ismi zikredilirse zorluk çekilmez.",
      faziletKisa: "Kansızlık ve vücudun güçlü olması için",
      kisaAciklama: "Kudreti en üstün.",
      uzunAciklama:
          "Pek güçlü; gücü her şeye yeten demektir. Allah Teâlâ, tam bir kudret sahibidir. Gücü, kuvveti sonsuzdur; bitmez, tükenmez. Bir sınıra sığmaz, ölçüye gelmez. Nicelik ve nitelik bakımından üstün kudrete sahiptir. Gücünün yetmeyeceği bir şey düşünülemez. O, her şeyi etkiler, ama hiç bir şey O’nu etkileyemez"),
  DataEsma(
      position: 55,
      name: "EL-METİN",
      ebced: 500,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Metin ismini hergün 500 defa zöhre saatinde okuyanlar; fakirlikten, hırstan, zulümden, kötü ahlaktan kurtulur. Zayıflığa düşmezler. Maddi ve manevi kuvvete ererler. Bir ay süreyle günde 1000 defa okuyanlar bazı sırlara vakıf olurlar. Kötü işlerle uğraşan kişinin, o huylarından vazgeçmesi için; Ya Kaviyy Ya Metin isimleri onar defa birlikte okunarak, Allah’dan o kişinin hidayete ermesi için dua edilir.",
      faziletKisa: "Maddi ve manevi sağlam olmak için okunur.",
      kisaAciklama: "Çok güçlü.",
      uzunAciklama:
          "Sonsuz kudrete sahip; son derece güçlü, kuvvetli; dayanıklı, sağlam demektir. Allah Teâlâ, sonsuz bir güce sahiptir. Fiillerinden dolayı zatına her hangi bir zorluk ve yorgunluk ilişmez. Kuvveti azalıp gevşemez. Hiçbir şey O’nu âciz bırakamaz. Hiç kimsenin yardımına da muhtaç değildir. Allah’ın “Kaviyy” ismi, kudretinin kemâlini ifâde eder. Bütün nesne ve olayları etkileyendir. “Metîn” ismi, kuvvetinin şiddetini bildirir. Dıştan gelebilecek hiç bir etkiyi kabul etmeyendir."),
  DataEsma(
      position: 56,
      name: "EL-VELİYY",
      ebced: 46,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Veliyy ismini zikreden kıyamet gününde hesabı kolayca görülür. Okuyanın derecesi Allah katında artar. İçi ve dışı temizlenir. Kötülüklerden uzak olur. Gece ve gündüz 10000 defa okuyan Allah’ın veli kullarından olur.",
      faziletKisa: "Her işinde Allah’ın yardımı için",
      kisaAciklama: "İnananların dostu.",
      uzunAciklama:
          "Dost ve yardımcı demektir. Allah Teâlâ, sevdiği kullarının dostudur. Onlara yardım eder; sıkıntılarını, darlıklarını giderir; ferahlık verir. Dünya ve âhiret işlerinde başarıya ulaştırır. Mü’minlerin yardımcısı ve koruyucusudur. Allah’tan başka gerçek dost ve yardımcı yoktur."),
  DataEsma(
      position: 57,
      name: "EL-HAMÎD",
      ebced: 68,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Hamid ismini zikredenlerin ahlakı, amelleri ve sözleri güzel olur, övgüye layık olur. Mahlukatın sevgisini kazanır. Maddi ve manevi olarak güçlenir. Bütün zor işleri kolaylaşır. 5 Vakit namazların ardından 100 defa okuyan salih kullardan olur. Dünya o kulun hizmetçisi olur.",
      faziletKisa: "Kazancın genişlemesi",
      kisaAciklama: "Hamd ve senaya layık olan.",
      uzunAciklama:
          "Övülmeye lâyık olan demektir. Allah Teâlâ, bütün isimleri, sıfatları ve fiilleriyle övülmeye tek lâyık olan zâttır. Bütün varlığın diliyle övülen ve şükredilendir. Allah Teâlâ, bizâtihî övülmeye lâyık olandır. Aynı zamanda insanların işledikleri iyi fiiller sebebiyle onları över ve mükâfâtlandırır."),
  DataEsma(
      position: 58,
      name: "EL-MUHSÎ ",
      ebced: 148,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Muhsi ismini zikredene bütün kalpler itaat eder. Okuyan kötü ahlaktan kurtulur. Unutkanlık kalmaz. Vücudundaki hastalıklardan şifa bulur. Allah zihin açıklığı verir, idrak ve anlayışı artar.",
      faziletKisa: "Zekanın kuvvetli olması için okunur.",
      kisaAciklama: "Tüm varlıkların sayısını bilen.",
      uzunAciklama:
          " Sonsuz ilmiyle her şeyin sayısını bilen, her yapılanı bir bir sayan demektir. Allah Teâlâ, sonsuz ilmi ile her şeyi kuşatmıştır. Her şeyi tek tek ve bütün ayrıntılarıyla bilendir. O’nun ilminden hiç bir şey hariç kalamaz. Bütün amellerin sayısını bilir, kıyâmet günü bunların hepsinin karşılığını verir. Hiç birini unutmaz ve atlamaz."),
  DataEsma(
      position: 59,
      name: "EL-MÜBDİ’",
      ebced: 56,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Mübdi ismini zikreden hikmet sahibi olur, hikmetli konuşur. Gizli olan işlerden haberdar olur. Hergün 56 defa Ya Mübdi ismini zikreden başladığı her işi başarıyla bitirir. İşe başlarken okunursa işte muvaffak olunur. Bir işe başlamada karar veremeyen 1000 defa bu ismi zikrederse karar verme gücü kazanır.",
      faziletKisa: "Her işte muvaffak olmak için okunur.",
      kisaAciklama: "Örneksiz yaratan.",
      uzunAciklama:
          "Yaratıkları maddesiz ve örneksiz olarak ilk baştan yaratan demektir. Allah Teâlâ, kâinâtı yaratırken daha önce bir benzeri ve örneği olmaksızın yaratmıştır. İşte esas yaratma denilen, ilk maddesi, örneği olmaksızın yaratmadır. Bu, yoktan var etmedir ve Allah’a mahsustur."),
  DataEsma(
      position: 60,
      name: "EL-MUİYD",
      ebced: 124,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Muid ismini zikredenlerin elinden gitmiş olan herşey yerine gelir. Bir işi bozulan 7 gün sabah namazının ardından 124 defa Ya Muid ismini zikrederse bozulan işi yoluna girer. Bir şeyi unutan kişi bu ismi okursa unuttuğunu hatırlar.",
      faziletKisa: "Elden kaçanı geriye kazanmak için okunur.",
      kisaAciklama: "Yeniden diriten.",
      uzunAciklama:
          "Yaratılmışları öldürdükten, yok ettikten sonra tekrar yaratan; öldükten sonra dirilten demektir. Allah Teâlâ, ilk defa yarattığı bütün insanları öldürecek, sonra tekrar diriltecek ve dünya hayatlarındaki inanç ve amellerinden hesaba çekecektir. Hayat, sadece dünya hayatından ibaret değildir. Tekrar bir hayat vardır ki gerçek ve devamlı hayat budur. İnsanlar buna göre hareket etmelidir."),
  DataEsma(
      position: 61,
      name: "EL-MUHYÎ",
      ebced: 68,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Muhyi ismini hergün 68 defa zikreden kişinin kalbine iman ve irfan nuru dolar. Kötüye giden işleri düzelir. Ya Muhyi ismini halvet ve riyazet ile zikreden manevi sırlara erer. Hastalıklara şifa verici olur. Nefsine hakim olamayan kişi geceleri okumaya devam ederse; nefsi kendisine riayet eder. Bir ay süre ile 5 vakit namazların ardından okuyan kişi tüm hastalıklardan şifa bulur.",
      faziletKisa: "İşlerin başarılı olması için okunur.",
      kisaAciklama: "Can veren.",
      uzunAciklama:
          "Can veren, yaşatan demektir. Allah Teâlâ, can bağışlayan, sağlık verendir. Ölüleri diriltendir. Ölü beldeleri gökten indirdiği su ile canlandıran, yeryüzünü bitkilerle donatandır. İlk olarak yaratan, can veren Allah, öldükten sonra tekrar hayat vermeye kâdirdir. Ölü kalpleri ilâhî hidâyet ve marifetle canlandırandır."),
  DataEsma(
      position: 62,
      name: "EL-MÜMİT",
      ebced: 490,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Mumit ismini zikreden, nefsinin şerrinden emin olur. Allah okuyanı Hak yoluna sokar. Düşmanlarının kötülüklerinden kurtulur. Nefsini yola getirir. Merih saatinde 409 defa okuyan hasımlarının şerrinden korunur. Sevdiğinden ayrılmaz.",
      faziletKisa: " Harama bakmamak, kötülükten vazgeçmek",
      kisaAciklama: "Ölümü yaratan.",
      uzunAciklama:
          "Öldüren, canlının hayatına son veren demektir. Allah Teâlâ, canlılara hayat verdiği gibi, ezelî ilmindeki takdire göre vakti gelince bu hayatlara son verendir. Fânî hayat, doğumla başlar, ölümle biter. Hayat dediğimiz ruhla cesedin birleşmesidir. Ölüm ise ruhun cesedden ayrılmasıdır. Ruh, ölmez. Başka bir hayatla devam eder. Kul için, ölüm sonrası başlayacak yeni ve devamlı hayata iyi hazırlık yapmak mühimdir."),
  DataEsma(
      position: 63,
      name: "EL-HAYY",
      ebced: 18,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Hayy ismini zikreden kişinin ömrü uzun ve afiyette olur. Kalbi tevhid nuru ile nurlanır. Hastaysa şifaya kavuşur. Ya Hayyu Ya Kayyum isimlerini birlikte 184 defa zikredenin her muradı gerçekleşir. Ya Allah Ya Hayy Ya Kayyum isimlerini birlikte zikreden Allah yolundan ayrılmaz.",
      faziletKisa: "Sözü tesirli ve herkesten tazim görür",
      kisaAciklama: "Sonsuz hayat sahibi.",
      uzunAciklama:
          "Diri, canlı olan; ölmek şânından olmayan demektir. Allah Teâlâ, bütün hayatların kaynağıdır. Hep diridir. Allah’ın hayy (diri) oluşu, yaratılmış varlıklarda olduğu gibi organik bir canlılık değildir. Hiç bir şeyden gâfil olmayan, hata yapmayan, kâinâtta kendisinden hiç bir şey gizli olmayan demektir."),
  DataEsma(
      position: 64,
      name: "EL-KAYYUM",
      ebced: 156,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Kayyum ismini zikreden kişinin tüm işleri zahmetsizce halolur. Teşebbüs ettiği her iş başarılı ve hayırlı olur. Uykusu hafifleşir, unutkanlıktan kurtulur. Ezber gücü artar.",
      faziletKisa: "Allah’ın izniyle her istekleri olur.",
      kisaAciklama: "Varlıkları diri tutan.",
      uzunAciklama:
          "Olup kimseye muhtaç değildir. Ezelî ve ebedîdir. Her şeyin varlık kazanması ve varlığını devam ettirmesi ancak Allah’ın yaratması, maddî mânevî ihtiyaçlarını gidermesi ve korumasıyla mümkündür. Yeri, gökleri ayakta tutan O’dur."),
  DataEsma(
      position: 65,
      name: "EL-VÂCİD",
      ebced: 14,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Vacid ismini 5 vakit namazların ardından 14 defa zikreden sahip olduğu ve elde ettiği şeyleri kaybetmez. Elindekiler zayi olmaz. Aradıklarını bulma gücüne sahip olur. Hileci ve büyücülerin kötülüklerinden korunur.",
      faziletKisa: "Kaybedilen şeyi bulmak için okunur.",
      kisaAciklama: "İstediğini bulan.",
      uzunAciklama:
          "İstediğini istediği zaman bulan; hiç bir şeye muhtaç olmayan demektir. Allah Teâlâ, dilediği şeye sahip olur. Bu hususta bir engelle karşılaşmaz. Bir şeyi ele geçirmek istediğinde zaman kollamaya, tedbir almaya, tuzak kurmaya ihtiyacı yoktur. İstediği, istediği zaman O’nun huzurundadır. Bütün yaratıklar O’nun emri ve tasarrufu altındadır."),
  DataEsma(
      position: 66,
      name: "EL-MÂCİD",
      ebced: 48,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Macid ismini zikredenin kalbi nurlanır. 5 Vakit namazların ardından 465 defa okuyanın malı, mülkü artar, muteber bir insan olur. Herkez tarafından sevilip sayılır. Hergün zöhre saatinde 48 defa okuyan her türlü bela ve musibetten uzak olur. Yaptığı dualar kabul görür.",
      faziletKisa: "Kazancın bolluğu için okunur.",
      kisaAciklama: "Kadri ve şanı büyük.",
      uzunAciklama:
          "Şânı ve kadri büyük; kerem ve cömertliği bol demektir. Allah Teâlâ, yardımı, ihsânı bol olandır. O’nun kullarına olan kerem ve cömertliği ifâdeye sığmaz, ölçüye gelmez. Bir taraftan kullarını iyi işler yapmaya muvaffak kılar; öbür taraftan onları güzel sıfatlara sahip olduklarından över."),
  DataEsma(
      position: 67,
      name: "EL-VÂHİD",
      ebced: 19,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Vahid ismini günde 1000 defa okuyanın kalbi; yorgunluktan ve bütün kötü düşüncelerden uzaklaşır. Mahlukatın şerrinden emin olur. Kalbi ve ruhu kuvvetlenir. Günde 4000 defa okuyanın kalbindeki tüm istek ve arzuları gerçekleşir.",
      faziletKisa: "İstediği olur, kalbi uyanır, aklı nur",
      kisaAciklama: "Fiillerinde, sıfatlarında ve zatında eşi benzeri olmayan.",
      uzunAciklama:
          "Bir olan, tek olan; zâtında, sıfatlarında, isimlerinde ve fiillerinde asla ortağı, dengi ve benzeri bulunmayan demektir. Allah Teâlâ, tektir, bölünüp parçalara ayrılmaz. Benzeri yoktur. Allah’ın bir olması sayı bakımından değildir, büyüklük ve yücelik açısındandır. O, bölünmesi ve artması mümkün olmayan tek bir varlıktır."),
  DataEsma(
      position: 68,
      name: "EL-EHAD",
      ebced: 13,
      zikirgunu0: "MERİH",
      zikirgunu1: "CUMA",
      faziletUzun: "'Yâ Vâhid' ism-i şerifini her gün 1000 defa okuyanın kalbindeki boş arzular ve düşünceler yerini Allah sevgisine bırakır. Allahu Tealanın 'EL-EHAD' ismi ile meşgul olan kimseler, nefsâni arzularını terk ederler. Kötü arkdaşları ile arkadaşlığını bırakır. Kalp ve gönüllerinde ilahi zevkler, ruhani lezzetler  meydana gelir. Her gün 19 defa Yâ 'Vâhid' ism-i şerifini okuyanın kalbi nur ile dolar, hayırlı her türlü murat ve istekleri yerine gelir.",
      faziletKisa: "Her türlü murat ve isteklerine kavuşmak için",
      kisaAciklama: "Bütün noksan sıfatlardan münezzeh olan yegâne zât",
      uzunAciklama:
          "Hidâyeti yaratan; istediği kulunu muradına erdiren, hayırlı yollara muvaffak kılan demektir. Allah Teâlâ, inanacak kalplerde hidâyeti yaratandır. Ebedî mutluluğu sağlayacak doğru yolu gösteren ve doğru yola ulaştırandır. Yolunu şaşırmışlara rehberlik edendir."),
  DataEsma(
      position: 69,
      name: "ES-SAMED",
      ebced: 134,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Samed ismini zikreden kişi; yeme, içme, giyim, kuşam gibi zaruri ihtiyaçların temininde kimseye muhtaç olmaz, zorluk çekmez. Azlığından veya çokluğundan dolayı elem ve keder duymaz. İrfan sahibi olur. Ya Samed ismini 520 defa okuyan açlık hissi duymaz. 100 Defa okuyan salaha erer. Yazılarak suyu içilirse içenin iradesi kuvvetlenir.",
      faziletKisa: "Hiç kimseye muhtaç olmamak",
      kisaAciklama: "Herkesin muhtaç olduğu.",
      uzunAciklama:
          "Her şeyin kendisine muhtaç olduğu, kendisinin hiç bir şeye muhtaç olmadığı; ihtiyaçların giderilmesi ve ızdırapların dindirilmesi için başvurulacak tek merci demektir. Allah Teâlâ, yaratıkların her türlü ihtiyaçlarını gidermek için başvurdukları tek başvuru kaynağıdır. Her türlü yaratığın her türlü ihtiyacını en mükemmel bir şekilde karşılar ve giderir. Kendisi ise hiç bir şeye muhtaç değildir."),
  DataEsma(
      position: 70,
      name: "EL-KADİR",
      ebced: 305,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Kadir ismini zikreden arzu ettiği her şeyde muvaffak olur. Hasta olan şifaya kavuşur. Her abdest aldıktan sonra 100 defa okuyan düşmanına karşı zafer kazanır.",
      faziletKisa: "İstediğini yapmaya gücü yetirmek",
      kisaAciklama: "Dilediğini yapan.",
      uzunAciklama:
          "Her şeye gücü yeten; kudret sahibi demektir. Allah Teâlâ, istediğini, istediği gibi yapmaya gücü yetendir. Her şeyi takdir eden, planlı ve ölçülü yapandır. Hiçbir şey O’nu âciz bırakamaz. Âlem, mutlak irâde ve kudrete sahip olan Allah tarafından yaratılmıştır."),
  DataEsma(
      position: 71,
      name: "EL-MUKTEDİR",
      ebced: 744,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Muktedir ismini zikreden kişi teşebbüs ettiği her işte başarılı olur. Hiç bir şeyden bıkmaz, usanmaz. Yaptığı işi ve sanatı kolaylıkla yapar. Ruhu kuvvetlenir. Cin, insan ve şeytan şerrinden uzak olur.",
      faziletKisa: "Her işte başarılı olmak için okunur.",
      kisaAciklama: "Dilediği gibi tasarruf eden.",
      uzunAciklama:
          "Tam bir kudret sahibi; her şeye gücü yeten demektir. Allah Teâlâ, kuvvet ve kudret sahipleri üzerinde istediği gibi tasarruf edendir. O’nun “Kâdir” oluşu, istediğini, istediği anda ve istediği şekilde yaratma gücüne sahip olması demektir. “Muktedir” olması ise, bilfiil gücünü yarattıklarında göstermesidir."),
  DataEsma(
      position: 72,
      name: "EL-MUKADDİM",
      ebced: 184,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Mukaddim ismini zikreden kişi kuvvet ve iktidar sahibi olur. Halk içinde heybetli olur. Makamı, mevkisi yükselir. Allah katında kadri artar. İstek ve dilekleri gerçekleşir. Savaş meydanında okunursa, düşmana karşı, okuyan kuvvetli olur.",
      faziletKisa: "Daima yükselmek için okunur.",
      kisaAciklama: "Dilediğini yükselten.",
      uzunAciklama:
          "İstediğini öne alan, ileri geçiren demektir. Allah Teâlâ, dilediği şeyi veya kimseyi öne alan, önde bulundurandır. Allah’ın daveti geneldir. Fakat hidâyet ettikleri davete uyar, ileri gider. Hidâyet etmedikleri geri kalır. Allah’ın emir ve yasakları bütün kullar içindir. Fakat Allah’ın muvaffak ettikleri bunlara uyar, yükselir; muvaffak etmedikleri geride kalır. O hâlde hem akıl ve irâdemizi Allah’a îmân ve itâat yönünde kullanmalı, hem de Allah’tan hidâyet istemelidir. “Mukaddim” ismi, “Muahhir” ismiyle beraber değerlendirilmelidir."),
  DataEsma(
      position: 73,
      name: "EL-MUAHHİR",
      ebced: 846,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Müahhir ismini okuyan tevbe edip takvaya erer. Kalbi Allah sevgisiyle dolar. İsteklerine kolayca kavuşur. Allah’ın rızasını kazanan kullardan olur. İbadet etmede zorlanmaz. Basiret gözü açılır. Kötü işlerden uzak durur.",
      faziletKisa: "Kötü birinin uzaklaştırılması için okunur.",
      kisaAciklama: "Dilediğini alçaltan.",
      uzunAciklama:
          "İstediğini geri koyan, arkaya bırakan demektir. Allah Teâlâ, hikmeti gereği geri bırakılması gerekenleri geri bırakır. “Mukaddim” ismi ile ilgili açıklamalarımız “Muahhir” ismi ile de ilgilidir. Esasen bu iki isim beraber değerlendirilmelidir. Bazan Allah Teâlâ, kulların istediklerini bir hikmeti gereği geri bırakır. İmtihan dünyasında olduğumuzu unutmamamız gerekir."),
  DataEsma(
      position: 74,
      name: "EL-EVVEL",
      ebced: 37,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Evvel ismini zikreden her isteğine ve dileğine kavuşur. Yolculuğa çıkarken okunursa okuyan yol sıkıntılarından kurtulur.",
      faziletKisa: "Her hayır işinde birinci olmak için okunur.",
      kisaAciklama: "Ezeli olan.",
      uzunAciklama:
          "İlk; varlığının başlangıcı olmayan demektir. Allah Teâlâ, bütün varlıklardan öncedir. Varlığının bir evveli, başlangıcı yoktur. O, kadîmdir, ezelîdir. Varlığı kendi zâtıyladır. Bütün varlıklar varlığını O’ndan almaktadır. Yaratmayı başlatan O’dur. “Evvel” ismini “Âhir” ismiyle beraber değerlendirmelidir."),
  DataEsma(
      position: 75,
      name: "EL-AHİR",
      ebced: 801,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Ahir ismini zikredenin düşmanları helak olur. Düşmanlarına karşı kuvvet kazanır. Kalbi Allah sevgisiyle dolar. Rızkı artar. Ya Evvel Ya Ahir isimlerini birlikte günde 838 defa zikreden; dünya ve ahirette üstün makamlara ulaşır. Tüm mahlukat okuyana hürmet ve itibarda bulunur.",
      faziletKisa: "Ömür uzunluğu için",
      kisaAciklama: "Ebedi olan.",
      uzunAciklama:
          "Varlığının sonu olmayan demektir. Allah Teâlâ, varlığı devamlı olandır. Varlığının başlangıcı olmadığı gibi sonu da yoktur. Allah, eşyanın evveli olması bakımından “Evvel”dir. Eşyanın sonu Allah’tan olması bakımından da “Âhir”dir. “Âhir” ismini, “Evvel” ismiyle beraber değerlendirmelidir."),
  DataEsma(
      position: 76,
      name: "EZ-ZAHİR",
      ebced: 1106,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Zahir ismini zikredenin kalbi nurlanır. Gizli işlere, sırlara erer. Kalbi üzerindeki perdeler açılır. Rüyasında istediği şeylerden haberdar olur. Güzel ahlak sahibi olur.",
      faziletKisa: "Her meselenin zuhuru için",
      kisaAciklama: "Varlığı açık olan. ",
      uzunAciklama:
          "Varlığı apaçık demektir. Allah Teâlâ, varlığını ve birliğini belgeleyen birçok delil bulunması açısından aşikârdır. Her şeyin üstünde olan, her şeyden yüce olandır. Allah’ın varlığı o kadar açıktır ki insanın gördüğü her şey, ibret nazarıyla baktığı takdirde onu, Allah’a götürür. “Zâhir” ismi, “Bâtın” ismiyle beraber değerlendirilmelidir."),
  DataEsma(
      position: 77,
      name: "EL-BATIN",
      ebced: 62,
      zikirgunu0: "AY",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Batın ismini zikreden; korktuklarından emin, kalbi geniş olur. İnsanlar, ona itaat edip, isteklerini yerine getirirler. Sözü dinlenir. Sohbeti etkili ve tesirli olur. İstediği şeylerden rüyada ve uyanık halde haberdar olur.",
      faziletKisa: "Nefsi mutmain ve kalbi geniş olması için",
      kisaAciklama: "Yüceliği gizli olan. ",
      uzunAciklama:
          "Zâtının görülmesi ve mâhiyetinin bilinmesi açısından gizli demektir. Allah Teâlâ, gizlidir. Çünkü O, gözle görülemez, künhüyle bilinemez. İnsan, her şeyiyle sınırlıdır. Allah ise, sınırsızdır. Sınırlı olan sınırsız olanı idrâk ve ihâta edemez. “Bâtın” ismi, “Zâhir” ismiyle beraber değerlendirilmelidir."),
  DataEsma(
      position: 78,
      name: "EL-VALİ",
      ebced: 47,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Vali ismini zikreden çeşitli afetlerden muhafaza olur. Makam ve mevkisi yükselir. Emrindeki herkes ondan korkar ve itaat eder. Emir ve istekleri yerine getirilir. Gece ve gündüz 10000 defa okuyan veli kullar mertebesine yükselir. Evliyalar ile görüşür.",
      faziletKisa: "Sözünün tesirli insanların sevmesi için",
      kisaAciklama: " Kainatı idare eden.",
      uzunAciklama:
          "Kâinatın tek hâkimi, yöneticisi demektir. Allah Teâlâ, bu büyük evreni ve her an meydana gelen bütün olayları tek başına yönetendir. Yaratıkların işlerini yerine koyandır. Bütün varlıkların tek hükümdârı olup onlar üzerinde istediği şekilde tasarrufta bulunandır. Dirilten ve öldüren O’dur. Hiç bir şey O’nun tasarrufunun dışında kalmaz."),
  DataEsma(
      position: 79,
      name: "EL-MÜTEÂLİ",
      ebced: 551,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Müteali ismini zikreden salaha erer. Hakim ve amirler nezdinde hürmet ve riayet görür. Onlardan beklediği istekleri kabul görür. Zorluklardan, şiddetten ve zahmetlerden kurtulur. Kötülüklerden muhafaza olur. Her bakımdan güçlenir ve kuvvetli olur. Makam ve mevkisi yükselir. Dua ve istekleri geri çevrilmez.",
      faziletKisa: "İstediği makama gelmek ve yüceliğe ermek",
      kisaAciklama: "Yüce olan.",
      uzunAciklama:
          "İzzet, şeref ve hükümranlık bakımından en yüce demektir. Allah Teâlâ, yaratılmışlar hakkında aklın mümkün gördüğü her şeyden, her hal ve tavırdan yücedir. Zât, sıfat ve fiilleri açısından yaratılmışlara benzemekten, denk ve ortağı bulunmaktan yücedir."),
  DataEsma(
      position: 80,
      name: "EL-BERR",
      ebced: 202,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Berr ismini okumaya devam edenler tüm mahlukatın şerrinden emin olur. Bütün hal ve hareketlerinde lutuf ve kereme mazhar olur. Dilleri hikmetlenir. Makamı, mertebesi, derecesi yükselir. Alkolik ve isyan halinde olanlar günde 700 defa Ya Berr ismini zikrederlerse; kötü alışkanlıklarından kurtulurlar, durumları düzelir.",
      faziletKisa: "Her halukarda iyilik bulmak",
      kisaAciklama: "İyilik ve ihsanı bol.",
      uzunAciklama:
          "İyilik ve bahşişi çok olan; va’dini yerine getiren demektir. Allah Teâlâ, kulları hakkında kolaylık isteyendir. Yaratıklarına karşı rahmet ve mağfireti; lütuf ve ihsânı bol olandır. Kullarının hep iyiliğini ister, kötülüklerini ve zorluk çekmelerini istemez. Yapılan kötülüklerin çoğunu bağışlar, örtbas eder."),
  DataEsma(
      position: 81,
      name: "ET-TEVVAB",
      ebced: 409,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Tevvab ismini zikreden kişinin tevbesi kabul olur. Zalimin zulmünden kurtulur. Para ve geçim sıkıntısı ortadan kalkar. Rızık kapıları okuyana açılır. Günde 409 defa Ya Tevvab ismini zikreden kişinin dünyevi ve uhrevi bütün işleri halolur.",
      faziletKisa: "Tövbelerin kabulu için",
      kisaAciklama: "Günahları bağışlayan.",
      uzunAciklama:
          "Tövbe eden kullarının tövbelerini kabul eden ve tövbede muvaffak kılan demektir. Allah Teâlâ, kullarını tövbeye sevkeden ve tövbelerini kabul edendir. Kendisine yönelen kullarının günahlarını affedendir. Tövbeleri kabul edip günahları bağışlayandır. Kul, işlediği günahlardan pişman olur, tövbeye yönelirse Allah onu tövbesinde başarılı kılar ve tövbesini kabul eder."),
  DataEsma(
      position: 82,
      name: "EL-MÜNTEKİM",
      ebced: 630,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Müntekim ismini okuyanlar düşmanlarının şerrinden korunurlar. Allah; okuyanın düşmanınına karşı intikamını alır. Hiç kimse Ya Müntekim ismini zikredene bir kötülük yapamaz.",
      faziletKisa: "Zülüm ve fenalıktan korunmak",
      kisaAciklama: "İntikam alan.",
      uzunAciklama:
          "Suçlulara, adâleti ile hak ettikleri cezayı veren demektir. Allah Teâlâ, suçluları hemen cezalandırmaz. Onları çeşitli yollarla uyarır. Yanlış davranışından dönmesi için kendisine fırsat ve yeterli zaman verir. Tövbe etmeyenleri cezalandırır. Fakat bu cezalandırma kendisi için değildir; zulüm ve gadre uğrayanlar içindir. Allah, dostlarından değil, düşmanlarından intikam alır."),
  DataEsma(
      position: 83,
      name: "EL-AFÜVV",
      ebced: 156,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Afüvv ismini zikreden kişi, iyi ahlak sahibi olur. Allah’ın mağfiretine nail olur, Allah’ın rızasını kazanan kullardan olur. Öfke anında 10 defa Ya Afüvv ismini zikredip ardından salatü selam okursa sakinleşir.",
      faziletKisa: "Rızık bolluğu Kalp huzuru için okunur.",
      kisaAciklama: "Affı çok olan.",
      uzunAciklama:
          "Hiç bir sorumluluk kalmayacak şekilde günahları affeden demektir. Allah Teâlâ, günahları kökünden kazıyıp tamamen yok eder. Kirâmen kâtibin meleklerinin kayıtlarını siler. Hatırlayıp mahçup olmasınlar diye kullarına işledikleri günahları da unutturur. Bu isimden nasip alan kul, bir taraftan devamlı Allah’tan af diler, diğer taraftan ümitsizliğe kapılmaz. Kullara karşı da çok affedici olur."),
  DataEsma(
      position: 84,
      name: "ER-RAUF",
      ebced: 286,
      zikirgunu0: "ZÜHAL",
      zikirgunu1: "CUMARTESİ",
      faziletUzun: "Ya Rauf ismini zikredenin kalbinde şefkat, ruhunda letafet meydana gelir. İnsanlar arasında sevgi, saygı ve şefkat görür. Eşiyle arasında geçimsizlik ve uyuşmazlık olan hergün utarit saatinde 286 defa Ya Rauf ismini zikrederse; sorunlar ortadan kalkar, sevgi ve muhabbet meydana gelir.",
      faziletKisa: "Hiçbir varlıktan zarar görmez.",
      kisaAciklama: "Çok merhametli.",
      uzunAciklama:
          "Çok şefkatli ve merhametli demektir. Allah Teâlâ, kullarına karşı ileri derecede merhamet ve şefkat sahibidir. Kullarının sıkıntılarını ortadan kaldırır. Allah kullarına akıl ve iyiyi kötüyü ayırt etme yeteneği vermiştir. Kullarını, işledikleri suçlardan dolayı hemen cezalandırmaz. Onlara hatalarından dönmesi için fırsat tanır. İnanan kullarının kusurlarını bağışlar, iyi amellerine fazlasıyla mükâfât verir."),
  DataEsma(
      position: 85,
      name: "MÂLİKEL-MÜLK",
      ebced: 212,
      zikirgunu0: "UTARİT",
      zikirgunu1: "ÇARŞAMBA",
      faziletUzun: "Ya Malikel Mülk ismini zikredenin mülkü çok olur. Fakirlikten kurtulur. Rütbe ve makamı yükselir. Kimseye muhtaç olmaz. Halk arasında sevilen, sayılan, aziz biri olur. Kalbinde süphe ve vesvese olan Ya Malikel Mülk zikrine devam ederse kurtulur. Halvet ve riyazet halinde 40 gün, günde 8000 defa okuyan ve okuma esnasında tütsü yaparsa bu ismin hadimi ile görüşür.",
      faziletKisa: "Mal ve kazanca zarar gelmez",
      kisaAciklama: "Her varlığın sahibi.",
      uzunAciklama:
          "Mülkün gerçek sâhibi; bütün varlık âleminin tek hâkimi demektir. Allah Teâlâ, bütün kâinatın tek sâhibi ve mâlikidir. Mülkünde istediği gibi tasarruf eder. Dilediğine mülk verir, dilediğine vermez. Dilediğine az verir, dilediğine çok verir. Mutlak hükümranlık O’na aittir. Bu isimden nasip alan kulda mal ve mülkün emânet olduğu şuuru yerleşir. Mal ve mülkü nasıl kullanacağını bilir; israf ve cimrilikten uzak durur. Nimet verene şükrünü tam yapar."),
  DataEsma(
      position: 86,
      name: "ZÜLCELÂLİVELİKRAM",
      ebced: 1098,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Zülcelali Velikram ismini zikreden her isteğine kavuşur. İzzet ve şerefe nail olur. Duaları kabül olur. Vesveseden korunur. Dünya; okuyanın hizmetçisi olur.",
      faziletKisa: "işlerin kolaylığı için okunur.",
      kisaAciklama: "Celal, azamet sahibi.",
      uzunAciklama:
          "Ululuk ve ikrâm sahibi demektir. Allah Teâlâ, yaratıkları tarafından yüceltilmeye ve övülmeye lâyık olandır. Kullarından dilediklerine, kendisine samimiyetle kulluk vazifelerini yapmayı sağlayan, mânevî derecelerini yükselten, dünyada ve âhirette onlara bol lütuflarda bulunandır. Ne kadar büyüklük, ululuk, yücelik varsa, hepsi Allah’a mahsustur."),
  DataEsma(
      position: 87,
      name: "EL-MUKSİT",
      ebced: 209,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Muksit ismini zikreden vesveseden, öfkeden, hiddetten, kalp sıkıntısından, şeytan şerrinden kurtulur. Bu isim ateş söndürme, insanı sakin kılma hususunda etkilidir.",
      faziletKisa: "Eşler arasını düzeltmek için okunur.",
      kisaAciklama: "Her işi birbirine denk yapan.",
      uzunAciklama:
          "Adâlet sahibi; bütün işlerini denk, birbirine uygun ve yerli yerinde yapan demektir. Allah Teâlâ, adâletle hükmedendir. En üstün adâlet ve merhamet sahibidir. Mazlumların haklarını zâlimlerden alandır. Dünyada dost düşman ayırımı yapmadan bütün kullarına rızık verir. Âhirette, dostları, yaptıklarının karşılığını fazlasıyla alacak, düşmanları ise sadece yaptıklarının karşılığı bir cezaya çarptırılacaklardır."),
  DataEsma(
      position: 88,
      name: "EL-CAMİ’",
      ebced: 114,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Cami ismini zikredenin dostları çoğalır, ayrılık ve hasret çekmez. Her maksadına kolayca ulaşır. Dünya ve ahiret saadetine erer. Bir şeyi zayi olan, eşi, hayvanı kaçan; Ya Cami ismini 114 defa okuyup ararsa aradığını bulur.",
      faziletKisa: "Küsleri barıştırmak için",
      kisaAciklama: "Mahşerde bir araya toplayan.",
      uzunAciklama:
          "İstediğini istediği zaman istediği yerde toplayan demektir. Allah Teâlâ, birbirine benzeyen şeyleri ve benzemeyen zıt şeyleri bir araya getirip toplayandır. Kıyâmet günü hesaba çekmek için yaratıkları toplayandır. Bütün iyilikleri, güzellikleri ve övgüleri zâtında toplayandır. Tabiatları zıt birçok unsuru bir araya getirendir. İnsanları birbirlerine sevdirip kalpleri ısındırandır."),
  DataEsma(
      position: 89,
      name: "EL-ĞANİYY",
      ebced: 1060,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Ğaniyy ismini zikreden; maddi ve manevi zenginliğe ulaşır, hiç bir şeye muhtaç olmaz. Zenginlerden olur.",
      faziletKisa: "Büyük servet ve geniş rızık okunur.",
      kisaAciklama: " İhtiyacı olmayan.",
      uzunAciklama:
          "Çok zengin olan; hiç bir şeye muhtaç olmayan demektir. Allah Teâlâ, her şey kendisine muhtaç olan; kendisi hiç bir şeye muhtaç olmayandır. Zât ve sıfatlarında her türlü ihtiyaçtan uzak olandır. Çok zengindir, hiçbir şeye ihtiyacı yoktur. Ama bütün varlıklar her konuda O’na muhtaçtır."),
  DataEsma(
      position: 90,
      name: "EL-MUĞNÎ",
      ebced: 110,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Muğni ismini zikreden bütün işlerinde kolaylık bulur. Fakirlikten kurtulur. Rızkı bol, maişesi geniş olur. Her gün zöhre saatinde 1100 defa okuyan ruhi bunalımdan ve fakirlikten kurtulur. Muhtaçlık çekmez.",
      faziletKisa: "Geçim genişliği, bol rızık ve zenginlik",
      kisaAciklama: "Müstağni kılan.",
      uzunAciklama:
          "İstediğini zengin eden demektir. Allah Teâlâ, dilediği kulun her türlü ihtiyacını karşılayandır. Fakir kullarını lütuf ve ihsânıyla zenginleştirir. Kanâat duygusu lütfedip gönül zenginliğine eriştirir. Kulun hal ve davranışlarını rızası yönüne yönlendirerek mânevî bakımdan zenginleştirir."),
  DataEsma(
      position: 91,
      name: "EL-MÂNİ’",
      ebced: 161,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Mani ismini zikreden çok korktuğu ve çekindiği şeylerden emin ve muhafaza olur. Gelecek zararlardan korunur. Ya Mani ismi insanı şehvet ve nefsin arzularından korur. Yatarken okunursa eşler arasındaki soğukluk kalkar. Yolculuk sırasında okunursa her türlü bela ve kazalardan uzak olunur.",
      faziletKisa: "Kaza beladan uzak olmak için",
      kisaAciklama: "Dilemediği şeyi engelleyen.",
      uzunAciklama:
          "Dilemediği şeylerin gerçekleşmesine izin vermeyen; kötü şeylere engel olan demektir. Allah Teâlâ, bazı isteklerin gerçekleşmesine müsaade etmez. Bütün isteklerimiz, Allah’ın dilemesi ve takdiriyle gerçekleşir. O’nun dilemediği bir şey olmaz. Dilediği şey de olur. Allah Teâlâ, sevdiği kullarının bazı kötü isteklerine engel olmak suretiyle onları zarardan korur."),
  DataEsma(
      position: 92,
      name: "ED-DÂRR",
      ebced: 1001,
      zikirgunu0: "MERİH",
      zikirgunu1: "SALI",
      faziletUzun: "Ya Darr ismi düşmana ve zalimlere çeşitli hastalıklar verdirme hususunda etkilidir. Bu ismi okuyan insanların şerrinden korunur.",
      faziletKisa: "Zararlı kişinin kahrı için",
      kisaAciklama: "Zarar verenleri yaratan.",
      uzunAciklama:
          "Zarar veren; elem ve zarar verici şeyleri yaratan demektir. Allah Teâlâ, bir kuluna her hangi bir zarar vermeyi dilerse, hiç kimse ona fayda veremez. Fayda vermek istediği kimseye de kimse zarar veremez. “Dârr” ismi, “Nâfi’” ismiyle beraber değerlendirilmelidir."),
  DataEsma(
      position: 93,
      name: "EN-NÂFİ’",
      ebced: 201,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Nafi ismini zikreden güzel bir hayat yaşar. Darlık, hastalık, musibet, stres ve sıkıntılardan kurtulur. Sırlara vakıf olur. Bir hastayı eliyle mesh ettiğinde, o hasta şifa ve afiyet bulur.",
      faziletKisa: "Hastalıklardan korunmak, şifa bulmak, zararlardan uzak durmak.",
      kisaAciklama: "Fayda verenleri yaratan.",
      uzunAciklama:
          "Fayda veren; dilediği kuluna hayırlı ve faydalı olanı veren demektir. Allah Teâlâ, zararlı gibi görünen her şeyi sezilmez yollarla faydalı hale getirendir. Çaresizlerin imdadına yetişendir. Kulunu hayra ve iyiliğe yöneltendir. “Nâfi” ismi, “Dârr” ismiyle beraber değerlendirilmelidir."),
  DataEsma(
      position: 94,
      name: "EN-NUR",
      ebced: 256,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Nûr ismini zikredenin kalbini iman nuru ve hikmet kaplar. Kalbinden taşan nur yüzündede görülür. Kalpleri ve bedenleri nurlanır. Okuyan doğru yolu bulur.",
      faziletKisa: "Doğruyu ve yanlışı görüp kalp nuruna sahip olmak.",
      kisaAciklama: "Alemleri nurlandıran.",
      uzunAciklama:
          "Nurlandıran, ışık veren, nur kaynağı; âlemleri nurlandıran; istediği simalara, zihinlere ve gönüllere nur yağdıran demektir. Allah Teâlâ, varlığı apaçık olandır. Nuru yaratan, onunla gökleri ve yeri aydınlatandır. Kulunun kalbini, gönlünü îmân nuruyla aydınlatarak hidâyete ermesini ve doğruyu bulmasını sağlayandır."),
  DataEsma(
      position: 95,
      name: "EL-HADİ",
      ebced: 20,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Hadi ismini zikreden hidayete erer. Hükmedecek kuvvete erer. Her işinde başarılı olur. Bütün mahlukat itaat eder. Rızkını kolay kazanır.",
      faziletKisa: "Çocukların itaatkar olması için okunur.",
      kisaAciklama: "Hidayet veren.",
      uzunAciklama:
          "Hidâyeti yaratan; istediği kulunu muradına erdiren, hayırlı yollara muvaffak kılan demektir. Allah Teâlâ, inanacak kalplerde hidâyeti yaratandır. Ebedî mutluluğu sağlayacak doğru yolu gösteren ve doğru yola ulaştırandır. Yolunu şaşırmışlara rehberlik edendir."),
  DataEsma(
      position: 96,
      name: "EL-BEDİ’",
      ebced: 86,
      zikirgunu0: "MÜŞTERİ",
      zikirgunu1: "PERŞEMBE",
      faziletUzun: "Ya Bedi ismini zikreden sanatında ilerler, başarılı olur. Görülmemiş icatlarda bulunur. Bilmediğini anlama gücü oluşur. Zarar ve ziyandan kurtulur. İşsiz olan iş bulur, işini kaybeden işine kavuşur.",
      faziletKisa: "Allah’ın yardımına nail olmak, maddî ve manevî güzellik için.",
      kisaAciklama: "Eşsiz yaratan.",
      uzunAciklama:
          "Varlıkları, eşi, benzeri ve örneği olmaksızın, sanatkârane bir şekilde yaratan demektir. Allah Teâlâ, her şeyi, bir numûnesi, benzeri olmaksızın yaratandır. Bu yaratma da eşsiz ve benzersiz bir yaratmadır. Yani akıllara durgunluk verecek derecede kusursuz ve mükemmel yaratmadır. Allah, zâtında, sıfatlarında ve fiillerinde benzeri görülmeyendir."),
  DataEsma(
      position: 97,
      name: "EL-BAKİ",
      ebced: 113,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Baki ismini zikredenin ömrü uzun ve sıhhatli olur.Afet ve belalardan uzak olur. Makam ve mevki edinir. Makamı, mülkü elinden gitmez. Korkularından kurtulur.",
      faziletKisa: "Ömrün uzunluğu, sıhhatin iyiliği için",
      kisaAciklama: "Ebedi olan.",
      uzunAciklama:
          "Ebedî olan; varlığının sonu olmayan demektir. Allah Teâlâ, varlığı devamlı olandır. Varlığının bir başlangıcı olmadığı gibi bir sonu da yoktur. Zâtı da, sıfatları da, fiilleri de bâkîdir, ebedîdir, devamlıdır. Mü’min de her hangi bir işi Allah rızası için yapmışsa, o fiil de ebedîlik kazanır. Yani kul, öbür âlemde mükâfâtını alır."),
  DataEsma(
      position: 98,
      name: "EL-VÂRİS",
      ebced: 707,
      zikirgunu0: "ZÜHRE",
      zikirgunu1: "CUMA",
      faziletUzun: "Ya Varis ismini zikreden kişi; mal, mülk ve itibar sahibi olur. İnsanlar arasında nüfuz ve merci sahibi olur. İsteklerine çabuk kavuşur. Kötülüklerden muhafaza olur.",
      faziletKisa: "Uzun ömür, bol mal, şeref ve rızık sahibi olmak.",
      kisaAciklama: "Her şeyin asıl sahibi olan.",
      uzunAciklama:
          "Varlığının sonu olmayan demektir. Allah Teâlâ, yaratılmış bütün varlıkları yok ettikten sonra bâkî kalan, mülkün gerçek sahibidir. Mülkü dilediğinden alır, dilediğine verir. Dünyada bulunan herkes ve evrende bulunan her şey fânîdir, geçicidir. İnsanlar ölümlü oldukları için sahip oldukları mal, mülk, servet de geçicidir."),
  DataEsma(
      position: 99,
      name: "ER-RAŞÎD",
      ebced: 514,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Raşîd ismini zikredenin ameli kabul görür. Duası, niyazı, yalvarış ve yakarışları kabul olur. Okuyan ıslah olur. Pişman olacağı şeyler yapmaz. İşleri kolaylaşır.",
      faziletKisa: "İçki ve zinadan kurtulmak ve güzel ahlak için",
      kisaAciklama: "Doğru yolu gösteren.",
      uzunAciklama:
          "İrşad eden; doğru yolu gösteren demektir. Allah Teâlâ, bütün işleri isabetli olan ve hedefine ulaşandır. Her şeyi ezelî takdirine göre yürüten, bir nizam ve hikmet üzere sonuna ulaştırandır. Lüzumsuz, faydasız, boş iş yapmayandır. Fiilleri dâimâ yerinde olandır. Devamlı olarak hakka isabet edendir. Hiç kimsenin yol göstermesine muhtaç olmayandır."),
  DataEsma(
      position: 100,
      name: "ES-SABUR",
      ebced: 298,
      zikirgunu0: "GÜNEŞ",
      zikirgunu1: "PAZAR",
      faziletUzun: "Ya Sabur ismini zikreden; şiddet ve zorluk görmez. Müşkülat anında Allah, sabır ve sebat ihsan eder. Teşebbüs ettiği her işi tamamlamadan bırakmaz. O işten acizlik getirmez, ondan vaz geçmeden sonunu getirir. Kalbi Allah sevgisi ile dolar. Bela, zulüm ve iftiralardan uzak olur.",
      faziletKisa: "Başladığı işi kolay bitirmek için",
      kisaAciklama: "Cezada acele etmeyen.",
      uzunAciklama:
          "Çok sabırlı demektir. Allah Teâlâ, günahkârları cezalandırma konusunda acele etmeyip lütfuyla bağışlayan ve erteleyendir. Günahkârlara mühlet tanır. Tövbe kapısını ölünceye kadar açık tutar. Kullarının af ve bağışlama dilemeleri için onlara fırsatlar tanır. Bu isimden nasip alan kul, ibâdetleri yapmada, haramlardan kaçınmada ve her türlü felâket karşısında sabırlı olur."),
];
